import { ProductItem } from "@/types/product";

export interface CatalogCollection {
  id: string;
  name: string;
  slug: string;
  description: string;
  heroImage: string;
  bannerUrl: string;
  featured: boolean;
  isActive: boolean;
  products?: Array<{
    product: ProductItem;
  }>;
  createdAt: string;
  updatedAt: string;
}

export interface CatalogCategory {
  id: string;
  name: string;
  slug: string;
  description: string;
  imageUrl: string;
  ogImage?: string;
  seoTitle?: string;
  seoDescription?: string;
  canonicalUrl?: string;
}

export interface CatalogJournalPost {
  id: string;
  title: string;
  slug: string;
  subtitle: string;
  excerpt: string;
  category: string;
  authorName: string;
  author?: { firstName: string; lastName: string; email?: string };
  coverImageUrl: string;
  isPublished: boolean;
  publishedAt: string;
  seoTitle: string;
  seoDescription: string;
  ogImage: string;
  canonicalUrl: string;
  relatedProductIds: string[];
  content: string;
}

export const FALLBACK_CATEGORIES: CatalogCategory[] = [
  {
    id: "cat-horlogerie",
    name: "Haute Horlogerie",
    slug: "haute-horlogerie",
    description: "Mechanical timepieces hand-crafted with in-house movements, sapphire crystals, and refined proportions.",
    imageUrl: "/images/products/watches/velora-signature-01/editorial.jpg",
    ogImage: "/images/products/watches/velora-signature-01/front.jpg",
    seoTitle: "Luxury Watches | VELORA Haute Horlogerie",
    seoDescription: "Explore precision mechanical watches crafted with in-house movements, sapphire crystal, and premium materials.",
    canonicalUrl: "https://velora-ateliers.com/watches",
  },
  {
    id: "cat-parfumerie",
    name: "High Perfumery",
    slug: "high-perfumery",
    description: "Pure extraits de parfum formulated in Grasse using rare resins and aged absolutes in crystal flacons.",
    imageUrl: "/images/products/fragrances/velora-noir-extrait/editorial.jpg",
    ogImage: "/images/products/fragrances/velora-noir-extrait/bottle-front.jpg",
    seoTitle: "High Perfumery Extraits | VELORA Grasse",
    seoDescription: "Discover pure extraits de parfum distilled in Grasse using rare botanical absolutes and precious resins.",
    canonicalUrl: "https://velora-ateliers.com/fragrances",
  },
];

export const FALLBACK_COLLECTIONS: CatalogCollection[] = [
  {
    id: "col-signature",
    name: "SIGNATURE",
    slug: "signature",
    description: "The definitive archetype of modern horological restraint and mechanical purity.",
    heroImage: "/images/products/watches/velora-signature-01/editorial.jpg",
    bannerUrl: "/images/products/watches/velora-signature-01/editorial.jpg",
    featured: true,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "col-noir",
    name: "NOIR",
    slug: "noir",
    description: "Monochromatic mastery forged in DLC-coated titanium and shadowed ruthenium.",
    heroImage: "/images/products/watches/velora-noir-01/editorial.jpg",
    bannerUrl: "/images/products/watches/velora-noir-01/editorial.jpg",
    featured: true,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "col-classic",
    name: "CLASSIC",
    slug: "classic",
    description: "Enduring proportions, porcelain white dials, and heritage complications refined for eternity.",
    heroImage: "/images/products/watches/velora-classic-01/editorial.jpg",
    bannerUrl: "/images/products/watches/velora-classic-01/editorial.jpg",
    featured: true,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "col-celestial",
    name: "The Celestial Complications",
    slug: "celestial-complications",
    description: "Timepieces inspired by astronomical geometry, planetary gearings, and meteorite dials.",
    heroImage: "/images/products/watches/velora-signature-02/editorial.jpg",
    bannerUrl: "/images/products/watches/velora-signature-02/editorial.jpg",
    featured: true,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "col-nocturne",
    name: "Nocturne Privé",
    slug: "nocturne-prive",
    description: "Intimate olfactory creations formulated exclusively for evening and contemplative wear.",
    heroImage: "/images/products/fragrances/velora-noir-extrait/lifestyle.jpg",
    bannerUrl: "/images/products/fragrances/velora-noir-extrait/lifestyle.jpg",
    featured: true,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
];

export const FALLBACK_PRODUCTS: ProductItem[] = [
  // 1. VELORA SIGNATURE 01
  {
    id: "prod-sig-01",
    name: "VELORA SIGNATURE 01",
    slug: "velora-signature-01",
    sku: "VEL-SIG-01",
    shortDescription: "Original 39mm architecture in surgical 904L steel, opaline ivory dial, hand-flamed blued steel hands, and saddle-stitched Epsom calfskin.",
    description: "The VELORA SIGNATURE 01 is the founding cornerstone of the Maison. Conceived as a study in pure horological symmetry, the 39mm case is sculpted from cryogenic-hardened 904L stainless steel, alternating between mirror-polished bevels and micro-vertical brushwork. The double-domed sapphire crystal has internal multi-layer anti-reflective treatment, hovering above an opaline warm ivory dial. Applied faceted baton indexes in 18k rose gold catch the ambient light, while leaf-shaped blued hands trace the passage of time driven by the in-house Calibre VA-01 automatic movement with 68 hours of reserve.",
    price: 14500,
    compareAtPrice: 16000,
    cost: 4800,
    status: "PUBLISHED",
    featured: true,
    tags: ["Automatic", "Sapphire", "904L Steel", "Signature", "Iconic", "In-House"],
    movement: "In-House Calibre VA-01 Automatic (28,800 vph)",
    powerReserve: "68 Hours",
    caseMaterial: "Cryogenic-Hardened 904L Stainless Steel",
    caseDiameter: "39.0 mm",
    caseThickness: "9.2 mm",
    crystal: "Double-Domed Sapphire with 5x Anti-Reflective Coating",
    waterResistance: "50m / 5 ATM",
    dialColor: "Warm Opaline Ivory with Rose Gold Batons",
    strapMaterial: "Cognac French Epsom Calfskin, Artisanal Saddle Stitch",
    clasp: "Custom Micro-Adjustable 904L Deployant",
    seoTitle: "VELORA SIGNATURE 01 | Automatic 39mm in 904L Steel",
    seoDescription: "The flagship VELORA SIGNATURE 01 automatic timepiece. In-house Calibre VA-01, 904L steel, double-domed sapphire, and opaline ivory dial.",
    category: { id: "cat-horlogerie", name: "Haute Horlogerie", slug: "haute-horlogerie" },
    collections: [
      { collection: { id: "col-signature", name: "SIGNATURE", slug: "signature", bannerUrl: "/images/products/watches/velora-signature-01/editorial.jpg" } },
      { collection: { id: "col-classic", name: "CLASSIC", slug: "classic", bannerUrl: "/images/products/watches/velora-classic-01/editorial.jpg" } },
    ],
    inventory: { quantity: 12, warehouseLocation: "Geneva Vault Alpha-1" },
    images: [
      { id: "sig01-img-1", url: "/images/products/watches/velora-signature-01/front.jpg", altText: "VELORA SIGNATURE 01 Studio Front Dial", sortOrder: 1, isPrimary: true },
      { id: "sig01-img-2", url: "/images/products/watches/velora-signature-01/angle.jpg", altText: "VELORA SIGNATURE 01 45-Degree Perspective", sortOrder: 2, isPrimary: false },
      { id: "sig01-img-3", url: "/images/products/watches/velora-signature-01/side.jpg", altText: "VELORA SIGNATURE 01 Side Profile & Beveling", sortOrder: 3, isPrimary: false },
      { id: "sig01-img-4", url: "/images/products/watches/velora-signature-01/dial-macro.jpg", altText: "VELORA SIGNATURE 01 Opaline Dial Macro", sortOrder: 4, isPrimary: false },
      { id: "sig01-img-5", url: "/images/products/watches/velora-signature-01/crown-macro.jpg", altText: "VELORA SIGNATURE 01 Knurled Crown Detail", sortOrder: 5, isPrimary: false },
      { id: "sig01-img-6", url: "/images/products/watches/velora-signature-01/case-macro.jpg", altText: "VELORA SIGNATURE 01 904L Steel Case Chamfer", sortOrder: 6, isPrimary: false },
      { id: "sig01-img-7", url: "/images/products/watches/velora-signature-01/strap-clasp.jpg", altText: "VELORA SIGNATURE 01 Saddle-Stitched Strap & Clasp", sortOrder: 7, isPrimary: false },
      { id: "sig01-img-8", url: "/images/products/watches/velora-signature-01/wrist-lifestyle.jpg", altText: "VELORA SIGNATURE 01 On Wrist Natural Light", sortOrder: 8, isPrimary: false },
      { id: "sig01-img-9", url: "/images/products/watches/velora-signature-01/editorial.jpg", altText: "VELORA SIGNATURE 01 Editorial Campaign", sortOrder: 9, isPrimary: false },
      { id: "sig01-img-10", url: "/images/products/watches/velora-signature-01/packaging.jpg", altText: "VELORA SIGNATURE 01 Presentation Box", sortOrder: 10, isPrimary: false },
    ],
    variants: [
      { id: "sig01-v1", sku: "VEL-SIG-01-COG", title: "Cognac Epsom Calfskin Strap", price: 14500, stock: 12, attributes: { strap: "Cognac Epsom", buckle: "Deployant" } },
      { id: "sig01-v2", sku: "VEL-SIG-01-NOIR", title: "Midnight Black Alligator Strap", price: 15200, stock: 8, attributes: { strap: "Midnight Black Alligator", buckle: "Deployant" } },
    ],
    macroDetails: [
      { part: "dial", title: "The Opaline Ivory Dial", subtitle: "Micro-Texture & Rose Gold Batons", description: "Subtle velvet ivory dial surface with applied diamond-faceted 18k rose gold baton indices.", imageUrl: "/images/products/watches/velora-signature-01/dial-macro.jpg" },
      { part: "hands", title: "The Leaf Hands", subtitle: "Flame-Blued Tempered Steel", description: "Heat-tempered blued steel feuille hands balanced to sub-milligram tolerances.", imageUrl: "/images/products/watches/velora-signature-01/front.jpg" },
      { part: "crown", title: "The Knurled Crown", subtitle: "Dual-Gasket Ergonomics", description: "Precision-fluted winding crown engineered with dual internal O-rings for tactile winding response.", imageUrl: "/images/products/watches/velora-signature-01/crown-macro.jpg" },
      { part: "case", title: "The 904L Steel Architecture", subtitle: "Vertical Satin & Mirror Anglage", description: "Cryogenically treated 904L steel with hand-lapped polished chamfers contrasting fine satin flanks.", imageUrl: "/images/products/watches/velora-signature-01/case-macro.jpg" },
      { part: "strap", title: "Artisanal Saddle-Stitched Leather", subtitle: "French Epsom Grain", description: "Full-grain vegetable-tanned Epsom calfskin hand-stitched with waxed linen thread.", imageUrl: "/images/products/watches/velora-signature-01/strap-clasp.jpg" },
      { part: "clasp", title: "Micro-Adjustable Deployant", subtitle: "Engineered Solid Steel", description: "Patented double-folding clasp providing 4mm of instant tool-free micro-adjustment.", imageUrl: "/images/products/watches/velora-signature-01/strap-clasp.jpg" },
    ],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // 2. VELORA SIGNATURE 02
  {
    id: "prod-sig-02",
    name: "VELORA SIGNATURE 02",
    slug: "velora-signature-02",
    sku: "VEL-SIG-02",
    shortDescription: "39mm 18K Rose Gold (4N) case framing a fumé slate charcoal dial with hand-applied 18k gold faceted batons and slate matte alligator.",
    description: "A nocturnal evolution of our signature silhouette. Machined from solid, sustainably mined 18K Rose Gold (4N), the SIGNATURE 02 pairs warm architectural gold with a mesmerising fumé charcoal sunburst dial that deepens from warm graphite at the center to pure obsidian at the perimeter. The sapphire crystal exhibition caseback reveals the hand-finished Calibre VA-01G with circular Côtes de Genève and a skeletonized rose gold tungsten rotor.",
    price: 26800,
    compareAtPrice: 29500,
    cost: 9200,
    status: "PUBLISHED",
    featured: true,
    tags: ["Automatic", "Rose Gold", "Fumé Dial", "Signature", "Limited Run"],
    movement: "In-House Calibre VA-01G Rose Gold Automatic (28,800 vph)",
    powerReserve: "68 Hours",
    caseMaterial: "Solid 18K Rose Gold (4N)",
    caseDiameter: "39.0 mm",
    caseThickness: "9.2 mm",
    crystal: "Double-Domed Sapphire with Internal Anti-Reflective Treatment",
    waterResistance: "50m / 5 ATM",
    dialColor: "Fumé Slate Charcoal Sunburst",
    strapMaterial: "Hand-Cut Matte Slate Mississippi Alligator",
    clasp: "Solid 18K Rose Gold Pin-Buckle & Deployant",
    seoTitle: "VELORA SIGNATURE 02 | 18K Rose Gold Luxury Watch",
    seoDescription: "Solid 18K Rose Gold case, fumé slate charcoal sunburst dial, and in-house automatic calibre VA-01G.",
    category: { id: "cat-horlogerie", name: "Haute Horlogerie", slug: "haute-horlogerie" },
    collections: [
      { collection: { id: "col-signature", name: "SIGNATURE", slug: "signature", bannerUrl: "/images/products/watches/velora-signature-02/editorial.jpg" } },
      { collection: { id: "col-celestial", name: "The Celestial Complications", slug: "celestial-complications", bannerUrl: "/images/products/watches/velora-signature-02/editorial.jpg" } },
    ],
    inventory: { quantity: 9, warehouseLocation: "Geneva Vault Alpha-2" },
    images: [
      { id: "sig02-img-1", url: "/images/products/watches/velora-signature-02/front.jpg", altText: "VELORA SIGNATURE 02 Studio Front View", sortOrder: 1, isPrimary: true },
      { id: "sig02-img-2", url: "/images/products/watches/velora-signature-02/angle.jpg", altText: "VELORA SIGNATURE 02 45-Degree Rose Gold Angle", sortOrder: 2, isPrimary: false },
      { id: "sig02-img-3", url: "/images/products/watches/velora-signature-02/side.jpg", altText: "VELORA SIGNATURE 02 Slender Side Profile", sortOrder: 3, isPrimary: false },
      { id: "sig02-img-4", url: "/images/products/watches/velora-signature-02/dial-macro.jpg", altText: "VELORA SIGNATURE 02 Fumé Slate Sunburst Dial Macro", sortOrder: 4, isPrimary: false },
      { id: "sig02-img-5", url: "/images/products/watches/velora-signature-02/crown-macro.jpg", altText: "VELORA SIGNATURE 02 18K Fluted Crown", sortOrder: 5, isPrimary: false },
      { id: "sig02-img-6", url: "/images/products/watches/velora-signature-02/case-macro.jpg", altText: "VELORA SIGNATURE 02 Rose Gold Case Anglage", sortOrder: 6, isPrimary: false },
      { id: "sig02-img-7", url: "/images/products/watches/velora-signature-02/strap-clasp.jpg", altText: "VELORA SIGNATURE 02 Slate Alligator Strap & Gold Clasp", sortOrder: 7, isPrimary: false },
      { id: "sig02-img-8", url: "/images/products/watches/velora-signature-02/wrist-lifestyle.jpg", altText: "VELORA SIGNATURE 02 On Wrist Evening Wear", sortOrder: 8, isPrimary: false },
      { id: "sig02-img-9", url: "/images/products/watches/velora-signature-02/editorial.jpg", altText: "VELORA SIGNATURE 02 Architectural Editorial", sortOrder: 9, isPrimary: false },
      { id: "sig02-img-10", url: "/images/products/watches/velora-signature-02/packaging.jpg", altText: "VELORA SIGNATURE 02 Walnut Vault Packaging", sortOrder: 10, isPrimary: false },
    ],
    variants: [
      { id: "sig02-v1", sku: "VEL-SIG-02-SLT", title: "Matte Slate Alligator Strap", price: 26800, stock: 5, attributes: { strap: "Matte Slate Alligator", buckle: "18K Deployant" } },
      { id: "sig02-v2", sku: "VEL-SIG-02-BRN", title: "Espresso Matte Alligator Strap", price: 26800, stock: 4, attributes: { strap: "Espresso Matte Alligator", buckle: "18K Deployant" } },
    ],
    macroDetails: [
      { part: "dial", title: "The Fumé Charcoal Dial", subtitle: "Degradé Sunburst Radiance", description: "Radial galvanic brushing that darkens gently toward the outer minute track.", imageUrl: "/images/products/watches/velora-signature-02/dial-macro.jpg" },
      { part: "hands", title: "18K Gold Faceted Hands", subtitle: "Mirror-Polished Anglage", description: "Solid 18k rose gold hands diamond-chamfered along each facet edge.", imageUrl: "/images/products/watches/velora-signature-02/front.jpg" },
      { part: "crown", title: "The Fluted 18K Crown", subtitle: "Direct-Drive Winding", description: "Deeply fluted 18K gold crown offering silky winding resistance.", imageUrl: "/images/products/watches/velora-signature-02/crown-macro.jpg" },
      { part: "case", title: "Solid 18K Rose Gold Case", subtitle: "4N Warmth Alloy", description: "Subtle copper-palladium alloy formulation preventing color degradation over decades.", imageUrl: "/images/products/watches/velora-signature-02/case-macro.jpg" },
      { part: "strap", title: "Matte Slate Alligator", subtitle: "Large Square Scales", description: "Hand-selected Mississippiensis alligator finished with seamless rolled edges.", imageUrl: "/images/products/watches/velora-signature-02/strap-clasp.jpg" },
      { part: "clasp", title: "18K Rose Gold Deployant", subtitle: "Ergonomic Sculpting", description: "Solid gold blade clasp contoured precisely to wrist curvature.", imageUrl: "/images/products/watches/velora-signature-02/strap-clasp.jpg" },
    ],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // 3. VELORA NOIR 01
  {
    id: "prod-noir-01",
    name: "VELORA NOIR 01",
    slug: "velora-noir-01",
    sku: "VEL-NOIR-01",
    shortDescription: "Monolithic 40mm Grade 5 DLC Titanium timepiece with a light-absorbing velvet black dial and dark ruthenium accents.",
    description: "Forged from Grade 5 Titanium and shielded with diamond-like carbon (DLC) coating, the VELORA NOIR 01 explores the absolute boundaries of stealth luxury. The dial features an ultra-matte velvet black surface that absorbs 99.2% of incident reflections, juxtaposed against polished anthracite-ruthenium indexes and luminescent hour pointers. Paired with a seamless textured FKM vulcanized rubber strap engineered for all-climate ergonomics.",
    price: 17200,
    compareAtPrice: 19000,
    cost: 5600,
    status: "PUBLISHED",
    featured: true,
    tags: ["Titanium", "DLC Coating", "Noir", "Stealth Luxury", "Automatic"],
    movement: "In-House Calibre VA-02T DLC Automatic",
    powerReserve: "72 Hours",
    caseMaterial: "Micro-Blasted Grade 5 Titanium with Diamond-Like Carbon (DLC)",
    caseDiameter: "40.0 mm",
    caseThickness: "9.6 mm",
    crystal: "Curved Sapphire Crystal with Dual Smoked Anti-Glare Treatment",
    waterResistance: "100m / 10 ATM",
    dialColor: "Ultra-Matte Velvet Noir with Ruthenium Batons",
    strapMaterial: "Textured FKM High-Performance Elastomer",
    clasp: "Black DLC Titanium Safety Folding Clasp",
    seoTitle: "VELORA NOIR 01 | DLC Titanium Automatic Watch",
    seoDescription: "Grade 5 Titanium treated in black DLC. Ultra-matte light-absorbing black dial with 72h power reserve.",
    category: { id: "cat-horlogerie", name: "Haute Horlogerie", slug: "haute-horlogerie" },
    collections: [
      { collection: { id: "col-noir", name: "NOIR", slug: "noir", bannerUrl: "/images/products/watches/velora-noir-01/editorial.jpg" } },
    ],
    inventory: { quantity: 16, warehouseLocation: "Geneva Vault Alpha-1" },
    images: [
      { id: "noir01-img-1", url: "/images/products/watches/velora-noir-01/front.jpg", altText: "VELORA NOIR 01 Studio Front View", sortOrder: 1, isPrimary: true },
      { id: "noir01-img-2", url: "/images/products/watches/velora-noir-01/angle.jpg", altText: "VELORA NOIR 01 45-Degree DLC Perspective", sortOrder: 2, isPrimary: false },
      { id: "noir01-img-3", url: "/images/products/watches/velora-noir-01/side.jpg", altText: "VELORA NOIR 01 Matte Black Case Side", sortOrder: 3, isPrimary: false },
      { id: "noir01-img-4", url: "/images/products/watches/velora-noir-01/dial-macro.jpg", altText: "VELORA NOIR 01 Velvet Black Dial Texture Macro", sortOrder: 4, isPrimary: false },
      { id: "noir01-img-5", url: "/images/products/watches/velora-noir-01/crown-macro.jpg", altText: "VELORA NOIR 01 Knurled DLC Titanium Crown", sortOrder: 5, isPrimary: false },
      { id: "noir01-img-6", url: "/images/products/watches/velora-noir-01/case-macro.jpg", altText: "VELORA NOIR 01 Micro-Blasted Titanium Case Detail", sortOrder: 6, isPrimary: false },
      { id: "noir01-img-7", url: "/images/products/watches/velora-noir-01/strap-clasp.jpg", altText: "VELORA NOIR 01 FKM Rubber Strap & DLC Deployant", sortOrder: 7, isPrimary: false },
      { id: "noir01-img-8", url: "/images/products/watches/velora-noir-01/wrist-lifestyle.jpg", altText: "VELORA NOIR 01 On Wrist Sport Luxury", sortOrder: 8, isPrimary: false },
      { id: "noir01-img-9", url: "/images/products/watches/velora-noir-01/editorial.jpg", altText: "VELORA NOIR 01 Monochromatic Editorial Campaign", sortOrder: 9, isPrimary: false },
      { id: "noir01-img-10", url: "/images/products/watches/velora-noir-01/packaging.jpg", altText: "VELORA NOIR 01 Matte Black Vault Packaging", sortOrder: 10, isPrimary: false },
    ],
    variants: [
      { id: "noir01-v1", sku: "VEL-NOIR-01-FKM", title: "Textured Obsidian FKM Strap", price: 17200, stock: 10, attributes: { strap: "Obsidian FKM Rubber", buckle: "DLC Safety Deployant" } },
      { id: "noir01-v2", sku: "VEL-NOIR-01-ALC", title: "Black Alcantara Technical Strap", price: 17800, stock: 6, attributes: { strap: "Black Alcantara", buckle: "DLC Safety Deployant" } },
    ],
    macroDetails: [
      { part: "dial", title: "The Velvet Black Void", subtitle: "Light-Absorbing Micro-Structure", description: "Specialized coating creating high-contrast depth against ruthenium-plated batons.", imageUrl: "/images/products/watches/velora-noir-01/dial-macro.jpg" },
      { part: "hands", title: "Ruthenium Shadow Hands", subtitle: "Anthracite Satin Bevels", description: "Deep gunmetal hands inlaid with custom charcoal Super-LumiNova.", imageUrl: "/images/products/watches/velora-noir-01/front.jpg" },
      { part: "crown", title: "Stealth DLC Crown", subtitle: "Screw-Down 100m Architecture", description: "Tactile knurled titanium crown coated in high-adhesion DLC with double seal.", imageUrl: "/images/products/watches/velora-noir-01/crown-macro.jpg" },
      { part: "case", title: "Grade 5 DLC Titanium", subtitle: "Micro-Blasted Monolith", description: "Weightless 64-gram case structure offering extraordinary tensile strength and scratch immunity.", imageUrl: "/images/products/watches/velora-noir-01/case-macro.jpg" },
      { part: "strap", title: "Textured FKM Elastomer", subtitle: "UV & Sweat Resistant", description: "Custom geometric underside channeling airflow for supreme wrist breathability.", imageUrl: "/images/products/watches/velora-noir-01/strap-clasp.jpg" },
      { part: "clasp", title: "DLC Safety Deployant", subtitle: "Dual Push-Button Security", description: "Micro-machined titanium mechanism locking firmly with satisfying acoustic feedback.", imageUrl: "/images/products/watches/velora-noir-01/strap-clasp.jpg" },
    ],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // 4. VELORA NOIR 02
  {
    id: "prod-noir-02",
    name: "VELORA NOIR 02",
    slug: "velora-noir-02",
    sku: "VEL-NOIR-02",
    shortDescription: "Openworked architectural skeleton in satin black zirconium ceramic with smoked sapphire dial and crimson sweep seconds.",
    description: "A radical vision of transparency and mechanical tension. The NOIR 02 strips away unnecessary mass to reveal the multi-tiered Calibre VA-SKEL in motion. Encased in high-density zirconium ceramic that is virtually impervious to scratches, the smoked sapphire dial suspends floating ruthenium hour markers, punctuated by a hand-lacquered crimson seconds needle. Each bridge is hand-beveled with mirror anglage by master artisans.",
    price: 34000,
    compareAtPrice: 38000,
    cost: 12500,
    status: "PUBLISHED",
    featured: true,
    tags: ["Skeleton", "Ceramic", "High Horology", "Noir", "Openworked"],
    movement: "Calibre VA-SKEL Openworked Skeleton Movement (Hand-Finished)",
    powerReserve: "70 Hours",
    caseMaterial: "High-Tech Black Zirconium Ceramic",
    caseDiameter: "41.0 mm",
    caseThickness: "10.1 mm",
    crystal: "Triple-Anti-Reflective Flat Sapphire Crystal Front & Back",
    waterResistance: "50m / 5 ATM",
    dialColor: "Openworked Smoked Sapphire with Crimson Accent",
    strapMaterial: "Ballistic Weave Technical Rubber with Calf Lining",
    clasp: "Ceramic & Titanium Dual Deployant",
    seoTitle: "VELORA NOIR 02 | High-Tech Ceramic Openworked Skeleton Watch",
    seoDescription: "Black zirconium ceramic case housing the hand-finished Calibre VA-SKEL skeleton movement with smoked sapphire crystal.",
    category: { id: "cat-horlogerie", name: "Haute Horlogerie", slug: "haute-horlogerie" },
    collections: [
      { collection: { id: "col-noir", name: "NOIR", slug: "noir", bannerUrl: "/images/products/watches/velora-noir-02/editorial.jpg" } },
    ],
    inventory: { quantity: 7, warehouseLocation: "Geneva Vault Alpha-2" },
    images: [
      { id: "noir02-img-1", url: "/images/products/watches/velora-noir-02/front.jpg", altText: "VELORA NOIR 02 Studio Front View", sortOrder: 1, isPrimary: true },
      { id: "noir02-img-2", url: "/images/products/watches/velora-noir-02/angle.jpg", altText: "VELORA NOIR 02 45-Degree Ceramic Angle", sortOrder: 2, isPrimary: false },
      { id: "noir02-img-3", url: "/images/products/watches/velora-noir-02/side.jpg", altText: "VELORA NOIR 02 Architectural Flank", sortOrder: 3, isPrimary: false },
      { id: "noir02-img-4", url: "/images/products/watches/velora-noir-02/dial-macro.jpg", altText: "VELORA NOIR 02 Skeleton Gear Train Macro", sortOrder: 4, isPrimary: false },
      { id: "noir02-img-5", url: "/images/products/watches/velora-noir-02/crown-macro.jpg", altText: "VELORA NOIR 02 Black Ceramic Crown", sortOrder: 5, isPrimary: false },
      { id: "noir02-img-6", url: "/images/products/watches/velora-noir-02/case-macro.jpg", altText: "VELORA NOIR 02 Zirconium Ceramic Case", sortOrder: 6, isPrimary: false },
      { id: "noir02-img-7", url: "/images/products/watches/velora-noir-02/strap-clasp.jpg", altText: "VELORA NOIR 02 Technical Strap & Clasp", sortOrder: 7, isPrimary: false },
      { id: "noir02-img-8", url: "/images/products/watches/velora-noir-02/wrist-lifestyle.jpg", altText: "VELORA NOIR 02 On Wrist Dramatic Shot", sortOrder: 8, isPrimary: false },
      { id: "noir02-img-9", url: "/images/products/watches/velora-noir-02/editorial.jpg", altText: "VELORA NOIR 02 Avant-Garde Editorial Campaign", sortOrder: 9, isPrimary: false },
      { id: "noir02-img-10", url: "/images/products/watches/velora-noir-02/packaging.jpg", altText: "VELORA NOIR 02 Ceramic Collection Presentation Box", sortOrder: 10, isPrimary: false },
    ],
    variants: [
      { id: "noir02-v1", sku: "VEL-NOIR-02-BAL", title: "Ballistic Weave Technical Rubber", price: 34000, stock: 4, attributes: { strap: "Ballistic Weave", buckle: "Ceramic Deployant" } },
      { id: "noir02-v2", sku: "VEL-NOIR-02-CER", title: "Full Matte Ceramic Link Bracelet", price: 39500, stock: 3, attributes: { strap: "Matte Ceramic Bracelet", buckle: "Titanium Deployant" } },
    ],
    macroDetails: [
      { part: "dial", title: "The Openworked Calibre", subtitle: "Hand-Beveled Ruthenium Bridges", description: "Internal gear train, balance wheel, and mainspring barrel fully exposed through smoked sapphire.", imageUrl: "/images/products/watches/velora-noir-02/dial-macro.jpg" },
      { part: "hands", title: "Skeleton Dauphine Hands", subtitle: "Crimson Sweep Pointer", description: "Openworked geometric hands counterbalanced with a surgical red lacquered needle.", imageUrl: "/images/products/watches/velora-noir-02/front.jpg" },
      { part: "crown", title: "Ceramic Fluted Crown", subtitle: "Smooth Wind Geometry", description: "Sintered ceramic crown body resistant to wear with integrated rubber grip ring.", imageUrl: "/images/products/watches/velora-noir-02/crown-macro.jpg" },
      { part: "case", title: "Zirconium Oxide Ceramic", subtitle: "Diamond-Hard Enclosure", description: "Sintered at 1,500°C for absolute surface hardness exceeding 1,500 Vickers.", imageUrl: "/images/products/watches/velora-noir-02/case-macro.jpg" },
      { part: "strap", title: "Hybrid Ballistic Textile", subtitle: "Water-Resistant Calf Lining", description: "Military-grade Cordura surface bonded to supple French calfskin underside.", imageUrl: "/images/products/watches/velora-noir-02/strap-clasp.jpg" },
      { part: "clasp", title: "Dual-Spring Ceramic Deployant", subtitle: "Zero-Wear Mechanism", description: "Deployant blades constructed from high-tensile titanium with black ceramic outer cap.", imageUrl: "/images/products/watches/velora-noir-02/strap-clasp.jpg" },
    ],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // 5. VELORA CLASSIC 01
  {
    id: "prod-cls-01",
    name: "VELORA CLASSIC 01",
    slug: "velora-classic-01",
    sku: "VEL-CLS-01",
    shortDescription: "Ultra-slim 38mm dress watch in mirror-polished 316L steel with a pristine cold-lacquered porcelain white dial and blued hands.",
    description: "Timeless proportion reimagined for modern formal attire. Measuring just 7.9mm in height, the VELORA CLASSIC 01 slips effortlessly beneath a double cuff. Its multi-layer cold-lacquered porcelain dial achieves a deep glassy luster, decorated with slender bespoke serif Roman numerals and heat-tempered blued steel feuille hands. Driven by the manual-wind Calibre VA-03M with 60 hours of smooth winding reserve.",
    price: 11800,
    compareAtPrice: 13000,
    cost: 3900,
    status: "PUBLISHED",
    featured: true,
    tags: ["Manual-Wind", "Ultra-Slim", "Porcelain Dial", "Classic", "Dress Watch"],
    movement: "In-House Calibre VA-03M Manual-Wind Ultra-Thin",
    powerReserve: "60 Hours",
    caseMaterial: "Mirror-Polished 316L Surgical Stainless Steel",
    caseDiameter: "38.0 mm",
    caseThickness: "7.9 mm",
    crystal: "Box-Domed Sapphire Crystal with Internal Anti-Reflective Treatment",
    waterResistance: "30m / 3 ATM",
    dialColor: "Porcelain White Multi-Layer Cold Lacquer",
    strapMaterial: "Genuine Shell Cordovan in Cognac Brown",
    clasp: "Polished Stainless Steel Pin Buckle with Engraved Monogram",
    seoTitle: "VELORA CLASSIC 01 | Ultra-Thin 38mm Dress Watch",
    seoDescription: "Ultra-slim 7.9mm manual-wind watch with multi-layer porcelain lacquer dial and blued feuille hands.",
    category: { id: "cat-horlogerie", name: "Haute Horlogerie", slug: "haute-horlogerie" },
    collections: [
      { collection: { id: "col-classic", name: "CLASSIC", slug: "classic", bannerUrl: "/images/products/watches/velora-classic-01/editorial.jpg" } },
    ],
    inventory: { quantity: 16, warehouseLocation: "Geneva Vault Alpha-1" },
    images: [
      { id: "cls01-img-1", url: "/images/products/watches/velora-classic-01/front.jpg", altText: "VELORA CLASSIC 01 Front Porcelain Dial", sortOrder: 1, isPrimary: true },
      { id: "cls01-img-2", url: "/images/products/watches/velora-classic-01/angle.jpg", altText: "VELORA CLASSIC 01 45-Degree Formal Perspective", sortOrder: 2, isPrimary: false },
      { id: "cls01-img-3", url: "/images/products/watches/velora-classic-01/side.jpg", altText: "VELORA CLASSIC 01 7.9mm Ultra-Slim Profile", sortOrder: 3, isPrimary: false },
      { id: "cls01-img-4", url: "/images/products/watches/velora-classic-01/dial-macro.jpg", altText: "VELORA CLASSIC 01 Porcelain Dial & Roman Numerals Macro", sortOrder: 4, isPrimary: false },
      { id: "cls01-img-5", url: "/images/products/watches/velora-classic-01/crown-macro.jpg", altText: "VELORA CLASSIC 01 Ultra-Slim Onion Crown", sortOrder: 5, isPrimary: false },
      { id: "cls01-img-6", url: "/images/products/watches/velora-classic-01/case-macro.jpg", altText: "VELORA CLASSIC 01 Mirror-Polished Stepped Bezel", sortOrder: 6, isPrimary: false },
      { id: "cls01-img-7", url: "/images/products/watches/velora-classic-01/strap-clasp.jpg", altText: "VELORA CLASSIC 01 Shell Cordovan Strap & Pin Buckle", sortOrder: 7, isPrimary: false },
      { id: "cls01-img-8", url: "/images/products/watches/velora-classic-01/wrist-lifestyle.jpg", altText: "VELORA CLASSIC 01 On Wrist Formal Black Tie", sortOrder: 8, isPrimary: false },
      { id: "cls01-img-9", url: "/images/products/watches/velora-classic-01/editorial.jpg", altText: "VELORA CLASSIC 01 Heritage Editorial Campaign", sortOrder: 9, isPrimary: false },
      { id: "cls01-img-10", url: "/images/products/watches/velora-classic-01/packaging.jpg", altText: "VELORA CLASSIC 01 Presentation Case", sortOrder: 10, isPrimary: false },
    ],
    variants: [
      { id: "cls01-v1", sku: "VEL-CLS-01-COG", title: "Cognac Horween Shell Cordovan", price: 11800, stock: 9, attributes: { strap: "Cognac Shell Cordovan", buckle: "Pin Buckle" } },
      { id: "cls01-v2", sku: "VEL-CLS-01-NOIR", title: "Noir Horween Shell Cordovan", price: 11800, stock: 7, attributes: { strap: "Noir Shell Cordovan", buckle: "Pin Buckle" } },
    ],
    macroDetails: [
      { part: "dial", title: "The Porcelain Lacquer Dial", subtitle: "Seven-Layer High-Gloss Enamel Luster", description: "Immaculate cold enamel surface cured and polished by hand to a vitreous depth.", imageUrl: "/images/products/watches/velora-classic-01/dial-macro.jpg" },
      { part: "hands", title: "Tempered Feuille Hands", subtitle: "Traditional Flame Blueing", description: "Graceful leaf hands thermally treated to a deep royal blue at 295°C.", imageUrl: "/images/products/watches/velora-classic-01/front.jpg" },
      { part: "crown", title: "The Ultra-Slim Onion Crown", subtitle: "Classic Horological Heritage", description: "Subtle vintage winding crown providing effortless engagement for manual daily ritual.", imageUrl: "/images/products/watches/velora-classic-01/crown-macro.jpg" },
      { part: "case", title: "Ultra-Thin 7.9mm Profile", subtitle: "Three-Piece Stepped Bezel", description: "Slender stepped case profile designed to sit completely flush against the wrist.", imageUrl: "/images/products/watches/velora-classic-01/case-macro.jpg" },
      { part: "strap", title: "Genuine Shell Cordovan", subtitle: "Equine Leather of Unrivaled Longevity", description: "Naturally vegetable-tanned equine leather prized for its non-creasing mirror surface.", imageUrl: "/images/products/watches/velora-classic-01/strap-clasp.jpg" },
      { part: "clasp", title: "Engraved Pin Buckle", subtitle: "Classic Formal Elegance", description: "Slender stainless steel ardillon buckle subtly engraved with the VELORA seal.", imageUrl: "/images/products/watches/velora-classic-01/strap-clasp.jpg" },
    ],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // 6. VELORA AUREL 01
  {
    id: "prod-aur-01",
    name: "VELORA AUREL 01",
    slug: "velora-aurel-01",
    sku: "VEL-AUR-01",
    shortDescription: "Sculptural 39.5mm timepiece in 18K Champagne Yellow Gold with integrated brick-link bracelet and warm satin champagne dial.",
    description: "The embodiment of modern Mediterranean radiance. Cast in VELORA's proprietary 18K Champagne Yellow Gold alloy—softer and more nuanced than conventional yellow gold—the AUREL 01 features a seamless integrated multi-row brick-link bracelet that drapes fluidly on the wrist. The warm satin-brushed champagne dial is elevated by baguette-cut gold indices and polished sword hands powered by the Calibre VA-04 Golden Reserve automatic movement.",
    price: 42500,
    compareAtPrice: 46000,
    cost: 16000,
    status: "PUBLISHED",
    featured: true,
    tags: ["Champagne Gold", "Integrated Bracelet", "Haute Horlogerie", "Jewelry Watch"],
    movement: "In-House Calibre VA-04 Golden Reserve Automatic",
    powerReserve: "65 Hours",
    caseMaterial: "Proprietary 18K Champagne Yellow Gold",
    caseDiameter: "39.5 mm",
    caseThickness: "8.8 mm",
    crystal: "Double-Domed Scratch-Proof Sapphire Crystal",
    waterResistance: "50m / 5 ATM",
    dialColor: "Vertical Satin Champagne Gold with Baguette Indexes",
    strapMaterial: "Solid 18K Champagne Gold Integrated Brick-Link Bracelet",
    clasp: "Concealed Butterfly Clasp in 18K Gold",
    seoTitle: "VELORA AUREL 01 | 18K Champagne Yellow Gold Watch",
    seoDescription: "Solid 18K Champagne Yellow Gold case with integrated articulated bracelet and in-house automatic calibre VA-04.",
    category: { id: "cat-horlogerie", name: "Haute Horlogerie", slug: "haute-horlogerie" },
    collections: [
      { collection: { id: "col-signature", name: "SIGNATURE", slug: "signature", bannerUrl: "/images/products/watches/velora-aurel-01/editorial.jpg" } },
      { collection: { id: "col-classic", name: "CLASSIC", slug: "classic", bannerUrl: "/images/products/watches/velora-classic-01/editorial.jpg" } },
    ],
    inventory: { quantity: 7, warehouseLocation: "Geneva Vault Alpha-2" },
    images: [
      { id: "aur01-img-1", url: "/images/products/watches/velora-aurel-01/front.jpg", altText: "VELORA AUREL 01 Front Studio View", sortOrder: 1, isPrimary: true },
      { id: "aur01-img-2", url: "/images/products/watches/velora-aurel-01/angle.jpg", altText: "VELORA AUREL 01 45-Degree Integrated Bracelet Angle", sortOrder: 2, isPrimary: false },
      { id: "aur01-img-3", url: "/images/products/watches/velora-aurel-01/side.jpg", altText: "VELORA AUREL 01 8.8mm Slender Gold Profile", sortOrder: 3, isPrimary: false },
      { id: "aur01-img-4", url: "/images/products/watches/velora-aurel-01/dial-macro.jpg", altText: "VELORA AUREL 01 Satin Champagne Dial & Baguette Markers", sortOrder: 4, isPrimary: false },
      { id: "aur01-img-5", url: "/images/products/watches/velora-aurel-01/crown-macro.jpg", altText: "VELORA AUREL 01 Onyx Cabochon Setting Crown", sortOrder: 5, isPrimary: false },
      { id: "aur01-img-6", url: "/images/products/watches/velora-aurel-01/case-macro.jpg", altText: "VELORA AUREL 01 18K Champagne Gold Case Anglage", sortOrder: 6, isPrimary: false },
      { id: "aur01-img-7", url: "/images/products/watches/velora-aurel-01/strap-clasp.jpg", altText: "VELORA AUREL 01 Brick-Link Bracelet & Invisible Clasp", sortOrder: 7, isPrimary: false },
      { id: "aur01-img-8", url: "/images/products/watches/velora-aurel-01/wrist-lifestyle.jpg", altText: "VELORA AUREL 01 On Wrist Golden Hour", sortOrder: 8, isPrimary: false },
      { id: "aur01-img-9", url: "/images/products/watches/velora-aurel-01/editorial.jpg", altText: "VELORA AUREL 01 Radiant Gold Editorial Campaign", sortOrder: 9, isPrimary: false },
      { id: "aur01-img-10", url: "/images/products/watches/velora-aurel-01/packaging.jpg", altText: "VELORA AUREL 01 Solid Oak Presentation Vault", sortOrder: 10, isPrimary: false },
    ],
    variants: [
      { id: "aur01-v1", sku: "VEL-AUR-01-BRC", title: "Solid 18K Brick-Link Bracelet", price: 42500, stock: 3, attributes: { bracelet: "Solid 18K Gold Brick-Link", clasp: "Concealed Butterfly" } },
      { id: "aur01-v2", sku: "VEL-AUR-01-LEA", title: "Honey Suede Alligator with 18K Clasp", price: 34500, stock: 4, attributes: { strap: "Honey Suede Alligator", clasp: "18K Gold Deployant" } },
    ],
    macroDetails: [
      { part: "dial", title: "The Satin Champagne Dial", subtitle: "Sunburst Texture & Baguette Facets", description: "Warm golden dial with vertical satin graining catching natural light reflections.", imageUrl: "/images/products/watches/velora-aurel-01/dial-macro.jpg" },
      { part: "hands", title: "Solid 18K Sword Hands", subtitle: "Mirrored Facets", description: "Hand-polished champagne gold hands offering pristine legibility.", imageUrl: "/images/products/watches/velora-aurel-01/front.jpg" },
      { part: "crown", title: "Integrated Gold Crown", subtitle: "Cabochon Setting", description: "Subtly recessed into the case flank with an inlaid natural onyx cabochon.", imageUrl: "/images/products/watches/velora-aurel-01/crown-macro.jpg" },
      { part: "case", title: "18K Champagne Gold Case", subtitle: "Proprietary Alloy", description: "Formulated with 75% pure gold, silver, and palladium for an understated pale yellow brilliance.", imageUrl: "/images/products/watches/velora-aurel-01/case-macro.jpg" },
      { part: "strap", title: "Integrated Brick-Link Bracelet", subtitle: "Articulated Fluidity", description: "Over 140 individually hand-finished gold links articulating seamlessly over the wrist.", imageUrl: "/images/products/watches/velora-aurel-01/strap-clasp.jpg" },
      { part: "clasp", title: "Concealed Butterfly Clasp", subtitle: "Invisible Closure", description: "Dual spring-loaded blades disappearing cleanly beneath the continuous bracelet links.", imageUrl: "/images/products/watches/velora-aurel-01/strap-clasp.jpg" },
    ],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // 7. VELORA NOIR (FRAGRANCE)
  {
    id: "prod-frg-noir",
    name: "VELORA NOIR",
    slug: "velora-noir-extrait",
    sku: "VEL-FRG-NOIR",
    shortDescription: "A dark nocturnal tapestry of Cade oil, birch tar, smoked leather, and wild Indonesian agarwood aged in dark oak casks.",
    description: "VELORA NOIR is an olfactory study of shadow, mineral silence, and sensual fire. Opening with crisp cracked black pepper and Italian bergamot, the core unfurls into dark smoked leather, Atlas cedarwood, and resinous frankincense. The drydown reveals an addictive foundation of wild Indonesian agarwood and vetiver bourbon, housed in our monolithic smoked obsidian flacon crowned with a heavy brushed gunmetal cap.",
    price: 420,
    compareAtPrice: 480,
    cost: 95,
    status: "PUBLISHED",
    featured: true,
    tags: ["Extrait de Parfum", "Smoked Leather", "Agarwood", "Noir", "Unisex"],
    concentration: "Extrait de Parfum (32% Concentration)",
    olfactiveFamily: "Smoked Leather & Rare Wood",
    gender: "Unisex / Contemplative",
    volumeMl: 100,
    seoTitle: "VELORA NOIR Extrait de Parfum | High Perfumery",
    seoDescription: "32% pure extrait concentration with aged Indonesian agarwood, smoked leather, birch tar, and frankincense.",
    category: { id: "cat-parfumerie", name: "High Perfumery", slug: "high-perfumery" },
    collections: [
      { collection: { id: "col-noir", name: "NOIR", slug: "noir", bannerUrl: "/images/products/fragrances/velora-noir-extrait/editorial.jpg" } },
      { collection: { id: "col-nocturne", name: "Nocturne Privé", slug: "nocturne-prive", bannerUrl: "/images/products/fragrances/velora-noir-extrait/lifestyle.jpg" } },
    ],
    inventory: { quantity: 42, warehouseLocation: "Grasse Vault Alpha-1" },
    images: [
      { id: "frg-noir-1", url: "/images/products/fragrances/velora-noir-extrait/bottle-front.jpg", altText: "VELORA NOIR 100ml Smoked Obsidian Flacon", sortOrder: 1, isPrimary: true },
      { id: "frg-noir-2", url: "/images/products/fragrances/velora-noir-extrait/bottle-angle.jpg", altText: "VELORA NOIR Gunmetal Cap & Glass Anglage", sortOrder: 2, isPrimary: false },
      { id: "frg-noir-3", url: "/images/products/fragrances/velora-noir-extrait/box.jpg", altText: "VELORA NOIR Velvet Presentation Box", sortOrder: 3, isPrimary: false },
      { id: "frg-noir-4", url: "/images/products/fragrances/velora-noir-extrait/lifestyle.jpg", altText: "VELORA NOIR Evening Sillage Editorial", sortOrder: 4, isPrimary: false },
      { id: "frg-noir-5", url: "/images/products/fragrances/velora-noir-extrait/ingredient-notes.jpg", altText: "VELORA NOIR Rare Agarwood & Resins Composition", sortOrder: 5, isPrimary: false },
      { id: "frg-noir-6", url: "/images/products/fragrances/velora-noir-extrait/editorial.jpg", altText: "VELORA NOIR High Perfumery Campaign", sortOrder: 6, isPrimary: false },
      { id: "frg-noir-7", url: "/images/products/fragrances/velora-noir-extrait/gift-set.jpg", altText: "VELORA NOIR Atelier Gift Coffret", sortOrder: 7, isPrimary: false },
      { id: "frg-noir-8", url: "/images/products/fragrances/velora-noir-extrait/bottle-box.jpg", altText: "VELORA NOIR Flacon with Outer Rigid Box", sortOrder: 8, isPrimary: false },
    ],
    variants: [
      { id: "frg-noir-v1", sku: "VEL-FRG-NOIR-100", title: "100ml Heavyweight Crystal Flacon", price: 420, stock: 24, attributes: { size: "100ml", presentation: "Full Crystal Flacon" } },
      { id: "frg-noir-v2", sku: "VEL-FRG-NOIR-50", title: "50ml Travel Flacon with Leather Sheath", price: 280, stock: 18, attributes: { size: "50ml", presentation: "Travel Leather Sheath" } },
    ],
    macroDetails: [
      { part: "flacon", title: "The Smoked Obsidian Flacon", subtitle: "Hand-Cut French Crystal (480g)", description: "Heavyweight dark smoked glass designed to shield volatile resin molecules from UV rays.", imageUrl: "/images/products/fragrances/velora-noir-extrait/bottle-front.jpg" },
      { part: "cap", title: "The Gunmetal Cap", subtitle: "Machined Magnetic Shield", description: "Solid brass cap coated in dark brushed ruthenium with satisfying magnetic snap closure.", imageUrl: "/images/products/fragrances/velora-noir-extrait/bottle-angle.jpg" },
      { part: "packaging", title: "The Presentation Vault", subtitle: "Textured Linen & Black Velvet", description: "Handcrafted rigid presentation box lined in deep black velvet with certificate of provenance.", imageUrl: "/images/products/fragrances/velora-noir-extrait/box.jpg" },
      { part: "lifestyle", title: "The Nocturnal Sillage", subtitle: "Over 14 Hours Longevity", description: "High molecular weight resins ensuring an intimate, magnetic trail that evolves throughout the night.", imageUrl: "/images/products/fragrances/velora-noir-extrait/lifestyle.jpg" },
      { part: "notes", title: "Wild Indonesian Agarwood", subtitle: "Cold-Extracted Resins", description: "Aged agarwood chips slow-distilled at low temperature to preserve balsamic notes.", imageUrl: "/images/products/fragrances/velora-noir-extrait/ingredient-notes.jpg" },
    ],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // 8. VELORA AURA (FRAGRANCE)
  {
    id: "prod-frg-aura",
    name: "VELORA AURA",
    slug: "velora-aura-extrait",
    sku: "VEL-FRG-AURA",
    shortDescription: "Luminous Calabrian bergamot, solar jasmine sambac, warm white ambergris, and sun-drenched coastal cedar.",
    description: "An olfactory ode to golden hour on the Mediterranean cliffside. VELORA AURA sparkles with solar Italian citrus and sheer white florals before resting into a radiant heart of jasmine sambac and creamy neroli. The drydown leaves an intoxicating warmth of white ambergris, golden musk, and cashmere wood. Housed in a crystalline frosted flacon that captures and diffracts golden rays.",
    price: 380,
    compareAtPrice: 420,
    cost: 85,
    status: "PUBLISHED",
    featured: true,
    tags: ["Extrait de Parfum", "Solar Citrus", "Jasmine", "Amber", "Luminous"],
    concentration: "Extrait de Parfum (30% Concentration)",
    olfactiveFamily: "Solar Floral & Golden Amber",
    gender: "Unisex / Luminous",
    volumeMl: 100,
    seoTitle: "VELORA AURA Extrait de Parfum | High Perfumery",
    seoDescription: "30% extrait concentration with Calabrian bergamot, solar jasmine sambac, white ambergris, and coastal cedar.",
    category: { id: "cat-parfumerie", name: "High Perfumery", slug: "high-perfumery" },
    collections: [
      { collection: { id: "col-signature", name: "SIGNATURE", slug: "signature", bannerUrl: "/images/products/watches/velora-signature-01/editorial.jpg" } },
    ],
    inventory: { quantity: 45, warehouseLocation: "Grasse Vault Alpha-1" },
    images: [
      { id: "frg-aura-1", url: "/images/products/fragrances/velora-aura-extrait/bottle-front.jpg", altText: "VELORA AURA 100ml Frosted Flacon", sortOrder: 1, isPrimary: true },
      { id: "frg-aura-2", url: "/images/products/fragrances/velora-aura-extrait/bottle-angle.jpg", altText: "VELORA AURA 18K Champagne Cap Angle", sortOrder: 2, isPrimary: false },
      { id: "frg-aura-3", url: "/images/products/fragrances/velora-aura-extrait/box.jpg", altText: "VELORA AURA Ivory & Gold Presentation Box", sortOrder: 3, isPrimary: false },
      { id: "frg-aura-4", url: "/images/products/fragrances/velora-aura-extrait/lifestyle.jpg", altText: "VELORA AURA Golden Hour Trail Editorial", sortOrder: 4, isPrimary: false },
      { id: "frg-aura-5", url: "/images/products/fragrances/velora-aura-extrait/ingredient-notes.jpg", altText: "VELORA AURA Jasmine & Citrus Notes", sortOrder: 5, isPrimary: false },
      { id: "frg-aura-6", url: "/images/products/fragrances/velora-aura-extrait/editorial.jpg", altText: "VELORA AURA Mediterranean Campaign", sortOrder: 6, isPrimary: false },
      { id: "frg-aura-7", url: "/images/products/fragrances/velora-aura-extrait/gift-set.jpg", altText: "VELORA AURA Atelier Coffret", sortOrder: 7, isPrimary: false },
      { id: "frg-aura-8", url: "/images/products/fragrances/velora-aura-extrait/bottle-box.jpg", altText: "VELORA AURA Packaging Ensemble", sortOrder: 8, isPrimary: false },
    ],
    variants: [
      { id: "frg-aura-v1", sku: "VEL-FRG-AURA-100", title: "100ml Frosted Crystal Flacon", price: 380, stock: 30, attributes: { size: "100ml", presentation: "Full Crystal Flacon" } },
      { id: "frg-aura-v2", sku: "VEL-FRG-AURA-50", title: "50ml Travel Flacon with Gold Sheath", price: 250, stock: 15, attributes: { size: "50ml", presentation: "Travel Gold Sheath" } },
    ],
    macroDetails: [
      { part: "flacon", title: "The Frosted Solar Flacon", subtitle: "Semi-Matte Champagne Glass", description: "Soft satin-frosted French glass diffusing natural sunlight with a warm golden inner glow.", imageUrl: "/images/products/fragrances/velora-aura-extrait/bottle-front.jpg" },
      { part: "cap", title: "The 18K Champagne Cap", subtitle: "Polished Gold Finish", description: "Heavyweight gold-tone stopper engraved with the minimalist VELORA crest.", imageUrl: "/images/products/fragrances/velora-aura-extrait/bottle-angle.jpg" },
      { part: "packaging", title: "The Ivory Gift Box", subtitle: "Gold Foil Monogram", description: "Premium warm ivory rigid box with gold hot-stamped typography and satin pull ribbon.", imageUrl: "/images/products/fragrances/velora-aura-extrait/box.jpg" },
      { part: "lifestyle", title: "Radiant Golden Hour Trail", subtitle: "Solar Diffusion", description: "Effortlessly elegant daytime projection leaving a clean, sun-warmed amber impression.", imageUrl: "/images/products/fragrances/velora-aura-extrait/lifestyle.jpg" },
      { part: "notes", title: "Calabrian Bergamot & Jasmine", subtitle: "Hand-Picked at Sunrise", description: "Cold-pressed citrus rind harmonized with night-blooming Grasse jasmine petals.", imageUrl: "/images/products/fragrances/velora-aura-extrait/ingredient-notes.jpg" },
    ],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // 9. VELORA ÉLAN (FRAGRANCE)
  {
    id: "prod-frg-elan",
    name: "VELORA ÉLAN",
    slug: "velora-elan-extrait",
    sku: "VEL-FRG-ELAN",
    shortDescription: "Highland juniper berry, fresh green cypress, crushed violet leaves, and damp Haitian vetiver.",
    description: "Crisp, sharp, and invigorating. VELORA ÉLAN captures the aristocratic vitality of alpine forests and morning mist. Top notes of wild juniper and crushed peppermint give way to powdery violet leaves and Siberian pine needle. The finish is anchored by noble Haitian vetiver roots and clean white cedarwood, housed in deep emerald glass with a polished palladium stopper.",
    price: 395,
    compareAtPrice: 440,
    cost: 88,
    status: "PUBLISHED",
    featured: true,
    tags: ["Extrait de Parfum", "Aromatic Green", "Vetiver", "Fresh Luxury", "Unisex"],
    concentration: "Extrait de Parfum (30% Concentration)",
    olfactiveFamily: "Green Aromatic & Noble Woods",
    gender: "Unisex / Fresh Aristocratic",
    volumeMl: 100,
    seoTitle: "VELORA ÉLAN Extrait de Parfum | High Perfumery",
    seoDescription: "30% extrait concentration with highland juniper, crisp cypress, crushed violet leaves, and Haitian vetiver.",
    category: { id: "cat-parfumerie", name: "High Perfumery", slug: "high-perfumery" },
    collections: [
      { collection: { id: "col-classic", name: "CLASSIC", slug: "classic", bannerUrl: "/images/products/watches/velora-classic-01/editorial.jpg" } },
    ],
    inventory: { quantity: 32, warehouseLocation: "Grasse Vault Alpha-1" },
    images: [
      { id: "frg-elan-1", url: "/images/products/fragrances/velora-elan-extrait/bottle-front.jpg", altText: "VELORA ÉLAN 100ml Forest Emerald Flacon", sortOrder: 1, isPrimary: true },
      { id: "frg-elan-2", url: "/images/products/fragrances/velora-elan-extrait/bottle-angle.jpg", altText: "VELORA ÉLAN Palladium Cap Perspective", sortOrder: 2, isPrimary: false },
      { id: "frg-elan-3", url: "/images/products/fragrances/velora-elan-extrait/box.jpg", altText: "VELORA ÉLAN Botanical Box", sortOrder: 3, isPrimary: false },
      { id: "frg-elan-4", url: "/images/products/fragrances/velora-elan-extrait/lifestyle.jpg", altText: "VELORA ÉLAN Alpine Freshness Editorial", sortOrder: 4, isPrimary: false },
      { id: "frg-elan-5", url: "/images/products/fragrances/velora-elan-extrait/ingredient-notes.jpg", altText: "VELORA ÉLAN Highland Juniper & Vetiver Notes", sortOrder: 5, isPrimary: false },
      { id: "frg-elan-6", url: "/images/products/fragrances/velora-elan-extrait/editorial.jpg", altText: "VELORA ÉLAN Campaign", sortOrder: 6, isPrimary: false },
      { id: "frg-elan-7", url: "/images/products/fragrances/velora-elan-extrait/gift-set.jpg", altText: "VELORA ÉLAN Gift Coffret", sortOrder: 7, isPrimary: false },
      { id: "frg-elan-8", url: "/images/products/fragrances/velora-elan-extrait/bottle-box.jpg", altText: "VELORA ÉLAN Bottle & Box", sortOrder: 8, isPrimary: false },
    ],
    variants: [
      { id: "frg-elan-v1", sku: "VEL-FRG-ELAN-100", title: "100ml Forest Emerald Flacon", price: 395, stock: 20, attributes: { size: "100ml", presentation: "Full Crystal Flacon" } },
      { id: "frg-elan-v2", sku: "VEL-FRG-ELAN-50", title: "50ml Travel Flacon with Silver Sheath", price: 260, stock: 12, attributes: { size: "50ml", presentation: "Travel Silver Sheath" } },
    ],
    macroDetails: [
      { part: "flacon", title: "The Forest Emerald Flacon", subtitle: "Deep Pine Mineral Tint", description: "Bespoke glass tinted with natural copper minerals yielding a rich forest emerald translucence.", imageUrl: "/images/products/fragrances/velora-elan-extrait/bottle-front.jpg" },
      { part: "cap", title: "The Palladium Cap", subtitle: "Mirror-Polished Noble Metal", description: "Solid brass coated in precious palladium for lifetime resistance against tarnish.", imageUrl: "/images/products/fragrances/velora-elan-extrait/bottle-angle.jpg" },
      { part: "packaging", title: "The Botanical Box", subtitle: "Forest Green Textured Paperboard", description: "Forest green presentation box debossed with microscopic botanical leaf patterns.", imageUrl: "/images/products/fragrances/velora-elan-extrait/box.jpg" },
      { part: "lifestyle", title: "Crisp Alpine Sillage", subtitle: "Invigorating Scent Architecture", description: "Clean, fresh, and remarkably enduring without synthetic harshness.", imageUrl: "/images/products/fragrances/velora-elan-extrait/lifestyle.jpg" },
      { part: "notes", title: "Highland Juniper & Vetiver", subtitle: "Steam-Distilled Botanical Essences", description: "Wild-harvested juniper berries distilled at high altitude for exceptional aromatic clarity.", imageUrl: "/images/products/fragrances/velora-elan-extrait/ingredient-notes.jpg" },
    ],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // 10. VELORA OUD (FRAGRANCE)
  {
    id: "prod-frg-oud",
    name: "VELORA OUD",
    slug: "velora-oud-extrait",
    sku: "VEL-FRG-OUD",
    shortDescription: "Rare wild Cambodian agarwood, Persian saffron threads, Taif rose absolute, and warm balsamic myrrh.",
    description: "The crown jewel of VELORA's High Perfumery atelier. Formulated at an exceptional 35% oil concentration, VELORA OUD uses ethically harvested wild Cambodian agarwood naturally matured for fifteen years. Layered with crimson threads of hand-picked Persian saffron, royal Taif rose petals, and smoldering amber resins. Encased in a heavyweight cognac-amber crystal flacon with a solid fluted bronze cap.",
    price: 550,
    compareAtPrice: 620,
    cost: 140,
    status: "PUBLISHED",
    featured: true,
    tags: ["Extrait de Parfum", "Cambodian Oud", "Taif Rose", "Saffron", "Opulent"],
    concentration: "Extrait de Parfum (35% Concentration)",
    olfactiveFamily: "Orientale Boisé & Spice",
    gender: "Unisex / Opulent",
    volumeMl: 100,
    seoTitle: "VELORA OUD Extrait de Parfum | High Perfumery",
    seoDescription: "35% concentration wild Cambodian agarwood matured 15 years, Persian saffron, and Taif rose.",
    category: { id: "cat-parfumerie", name: "High Perfumery", slug: "high-perfumery" },
    collections: [
      { collection: { id: "col-nocturne", name: "Nocturne Privé", slug: "nocturne-prive", bannerUrl: "/images/products/fragrances/velora-noir-extrait/lifestyle.jpg" } },
    ],
    inventory: { quantity: 25, warehouseLocation: "Grasse Vault Alpha-2" },
    images: [
      { id: "frg-oud-1", url: "/images/products/fragrances/velora-oud-extrait/bottle-front.jpg", altText: "VELORA OUD 100ml Amber Cognac Flacon", sortOrder: 1, isPrimary: true },
      { id: "frg-oud-2", url: "/images/products/fragrances/velora-oud-extrait/bottle-angle.jpg", altText: "VELORA OUD Fluted Bronze Stopper", sortOrder: 2, isPrimary: false },
      { id: "frg-oud-3", url: "/images/products/fragrances/velora-oud-extrait/box.jpg", altText: "VELORA OUD Lacquered Box", sortOrder: 3, isPrimary: false },
      { id: "frg-oud-4", url: "/images/products/fragrances/velora-oud-extrait/lifestyle.jpg", altText: "VELORA OUD Imperial Sillage Editorial", sortOrder: 4, isPrimary: false },
      { id: "frg-oud-5", url: "/images/products/fragrances/velora-oud-extrait/ingredient-notes.jpg", altText: "VELORA OUD Aged Agarwood & Saffron Notes", sortOrder: 5, isPrimary: false },
      { id: "frg-oud-6", url: "/images/products/fragrances/velora-oud-extrait/editorial.jpg", altText: "VELORA OUD High Perfumery Campaign", sortOrder: 6, isPrimary: false },
      { id: "frg-oud-7", url: "/images/products/fragrances/velora-oud-extrait/gift-set.jpg", altText: "VELORA OUD Gift Set", sortOrder: 7, isPrimary: false },
      { id: "frg-oud-8", url: "/images/products/fragrances/velora-oud-extrait/bottle-box.jpg", altText: "VELORA OUD Presentation Ensemble", sortOrder: 8, isPrimary: false },
    ],
    variants: [
      { id: "frg-oud-v1", sku: "VEL-FRG-OUD-100", title: "100ml Cognac Crystal Flacon", price: 550, stock: 15, attributes: { size: "100ml", presentation: "Full Crystal Flacon" } },
      { id: "frg-oud-v2", sku: "VEL-FRG-OUD-50", title: "50ml Travel Flacon with Bronze Sheath", price: 340, stock: 10, attributes: { size: "50ml", presentation: "Travel Bronze Sheath" } },
    ],
    macroDetails: [
      { part: "flacon", title: "The Amber Cognac Crystal", subtitle: "Hand-Blown Heavy Crystal", description: "Warm amber-tinted crystal reflecting liquid gold hues under candlelight.", imageUrl: "/images/products/fragrances/velora-oud-extrait/bottle-front.jpg" },
      { part: "cap", title: "The Fluted Bronze Cap", subtitle: "Antiqued Bronze Finish", description: "Cast bronze cap featuring classical vertical fluting and monogram seal.", imageUrl: "/images/products/fragrances/velora-oud-extrait/bottle-angle.jpg" },
      { part: "packaging", title: "The Royal Lacquered Box", subtitle: "Cognac Satin & Bronze Foil", description: "Opulent presentation box featuring bronze metallic foil and velvet-padded flacon bed.", imageUrl: "/images/products/fragrances/velora-oud-extrait/box.jpg" },
      { part: "lifestyle", title: "The 24-Hour Imperial Trail", subtitle: "Exceptional Concentration", description: "A profound, hypnotic trail that lingers gracefully on fabric and skin for over 24 hours.", imageUrl: "/images/products/fragrances/velora-oud-extrait/lifestyle.jpg" },
      { part: "notes", title: "15-Year Aged Cambodian Oud", subtitle: "Rare Wild Harvest", description: "Rich, animalic, yet remarkably smooth agarwood aged to perfection in Grasse vaults.", imageUrl: "/images/products/fragrances/velora-oud-extrait/ingredient-notes.jpg" },
    ],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // 11. VELORA SANTÉ (FRAGRANCE)
  {
    id: "prod-frg-sante",
    name: "VELORA SANTÉ",
    slug: "velora-sante-extrait",
    sku: "VEL-FRG-SANTE",
    shortDescription: "Delicate Imperial white tea, crisp Bartlett pear, dewy Damask rosewater, and mineral crystalline musk.",
    description: "A tranquil breath of serenity and graceful restraint. VELORA SANTÉ opens with dewy white peach, sparkling Bartlett pear, and steepings of rare silver needle white tea. As it warms against the skin, tender Damask rose petals and iris powder bloom over a whisper-soft base of mineral musks and blond sandalwood. Housed in a fluted glass column with a warm rose gold collar.",
    price: 360,
    compareAtPrice: 400,
    cost: 75,
    status: "PUBLISHED",
    featured: true,
    tags: ["Extrait de Parfum", "White Tea", "Pear", "Damask Rose", "Ethereal"],
    concentration: "Extrait de Parfum (28% Concentration)",
    olfactiveFamily: "Soft Floral & Mineral Tea",
    gender: "Unisex / Ethereal",
    volumeMl: 100,
    seoTitle: "VELORA SANTÉ Extrait de Parfum | High Perfumery",
    seoDescription: "28% extrait concentration featuring rare silver needle white tea, crisp pear, Damask rose, and crystalline musk.",
    category: { id: "cat-parfumerie", name: "High Perfumery", slug: "high-perfumery" },
    collections: [
      { collection: { id: "col-signature", name: "SIGNATURE", slug: "signature", bannerUrl: "/images/products/watches/velora-signature-01/editorial.jpg" } },
    ],
    inventory: { quantity: 36, warehouseLocation: "Grasse Vault Alpha-1" },
    images: [
      { id: "frg-sante-1", url: "/images/products/fragrances/velora-sante-extrait/bottle-front.jpg", altText: "VELORA SANTÉ 100ml Fluted Flacon", sortOrder: 1, isPrimary: true },
      { id: "frg-sante-2", url: "/images/products/fragrances/velora-sante-extrait/bottle-angle.jpg", altText: "VELORA SANTÉ Rose Gold Collar Detail", sortOrder: 2, isPrimary: false },
      { id: "frg-sante-3", url: "/images/products/fragrances/velora-sante-extrait/box.jpg", altText: "VELORA SANTÉ Ivory & Blush Box", sortOrder: 3, isPrimary: false },
      { id: "frg-sante-4", url: "/images/products/fragrances/velora-sante-extrait/lifestyle.jpg", altText: "VELORA SANTÉ Serene Morning Editorial", sortOrder: 4, isPrimary: false },
      { id: "frg-sante-5", url: "/images/products/fragrances/velora-sante-extrait/ingredient-notes.jpg", altText: "VELORA SANTÉ White Tea & Pear Notes", sortOrder: 5, isPrimary: false },
      { id: "frg-sante-6", url: "/images/products/fragrances/velora-sante-extrait/editorial.jpg", altText: "VELORA SANTÉ Botanical Campaign", sortOrder: 6, isPrimary: false },
      { id: "frg-sante-7", url: "/images/products/fragrances/velora-sante-extrait/gift-set.jpg", altText: "VELORA SANTÉ Gift Coffret", sortOrder: 7, isPrimary: false },
      { id: "frg-sante-8", url: "/images/products/fragrances/velora-sante-extrait/bottle-box.jpg", altText: "VELORA SANTÉ Presentation Packaging", sortOrder: 8, isPrimary: false },
    ],
    variants: [
      { id: "frg-sante-v1", sku: "VEL-FRG-SANTE-100", title: "100ml Fluted Glass Column Flacon", price: 360, stock: 22, attributes: { size: "100ml", presentation: "Full Crystal Flacon" } },
      { id: "frg-sante-v2", sku: "VEL-FRG-SANTE-50", title: "50ml Travel Flacon with Rose Gold Sheath", price: 240, stock: 14, attributes: { size: "50ml", presentation: "Travel Rose Gold Sheath" } },
    ],
    macroDetails: [
      { part: "flacon", title: "The Fluted Glass Column", subtitle: "Classical Architectural Grooves", description: "Slender fluted glass column creating prismatic light reflections.", imageUrl: "/images/products/fragrances/velora-sante-extrait/bottle-front.jpg" },
      { part: "cap", title: "The Rose Gold Collar", subtitle: "Delicate Blush Metallic", description: "Subtle 18k rose gold plated collar and cap with blush silk tassel accent.", imageUrl: "/images/products/fragrances/velora-sante-extrait/bottle-angle.jpg" },
      { part: "packaging", title: "The Ivory & Blush Box", subtitle: "Rose Gold Foil Detailing", description: "Minimalist cream presentation box featuring understated rose gold lettering.", imageUrl: "/images/products/fragrances/velora-sante-extrait/box.jpg" },
      { part: "lifestyle", title: "Serene Ethereal Projection", subtitle: "Clean Skin Intimacy", description: "Light, translucent sillage evoking quiet mornings in Japanese tea gardens.", imageUrl: "/images/products/fragrances/velora-sante-extrait/lifestyle.jpg" },
      { part: "notes", title: "Imperial White Tea & Damask Rose", subtitle: "Gentle Cold Infusion", description: "First-flush young tea buds brewed cold to retain subtle floral tannins.", imageUrl: "/images/products/fragrances/velora-sante-extrait/ingredient-notes.jpg" },
    ],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
];

export const FALLBACK_JOURNAL_POSTS: CatalogJournalPost[] = [
  {
    id: "post-1",
    title: "The Architecture of the Free-Sprung Balance Wheel",
    slug: "architecture-of-the-free-sprung-balance-wheel",
    subtitle: "Why variable inertia balances define high-precision Geneva chronometry",
    excerpt: "An exploration of variable inertia balances, thermal compensation curves, and how VELORA achieves 72 hours of uninterrupted isochronism.",
    category: "Horology",
    authorName: "Jean-Luc Vaneau, Master Watchmaker",
    author: { firstName: "Jean-Luc", lastName: "Vaneau" },
    coverImageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1600&q=85",
    isPublished: true,
    publishedAt: "2026-08-15T10:00:00.000Z",
    seoTitle: "Architecture of Free-Sprung Balance Wheels | VELORA Journal",
    seoDescription: "Discover the micromechanical physics behind VELORA's variable inertia balance wheels and high-precision chronometry.",
    ogImage: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=85",
    canonicalUrl: "https://velora-ateliers.com/journal/architecture-of-the-free-sprung-balance-wheel",
    relatedProductIds: ["prod-sig-01", "prod-sig-02"],
    content: `At the apex of fine watchmaking, time is not merely counted; it is disciplined. Among the components residing within a mechanical movement, none exerts greater authority over precision than the regulating organ—specifically, the balance wheel and hairspring assembly.

In traditional watchmaking, regulation is frequently accomplished via an index-regulated curb pin that alters the active length of the hairspring. While expedient, this method introduces micro-friction and subtle asymmetry across positional shifts. VELORA avoids this compromise in favor of the free-sprung balance.

> "A free-sprung balance wheel does not constrain the breath of the spring. It relies on inertia weights tuned by hand to within one-hundredth of a milligram."

By utilizing four gold inertial micro-screws countersunk along the rim of the Glucydur balance, our master horologists adjust poise and rate without touching the active length of the terminal Breguet overcoil. The result is pure, uninterrupted isochronism that remains stable against daily shocks and temperature changes.

## Hand-Finished Beveling and Internal Angles

Beyond mathematical physics, mechanical excellence requires tactile artistry. Every bridge securing our regulating organ is mirror-polished using gentian wood pegs and diamond paste. Sharp internal angles—the hallmark that automated machines cannot replicate—are hand-carved with gravers under 40x magnification.

When observing the heartbeat of Calibre VA-01 through the sapphire caseback, one does not merely observe a machine. One witnesses decades of Swiss craft beating at 28,800 vibrations per hour.`,
  },
  {
    id: "post-2",
    title: "Nocturne: The Craft of 35% Extrait Extraction",
    slug: "nocturne-dark-art-of-extraction",
    subtitle: "Subcritical CO2 extraction of rare Grasse botanicals and smoked labdanum",
    excerpt: "Inside our Grasse compounding laboratory: extracting volatile floral absolutes under high pressure to preserve delicate olfactory facets.",
    category: "Perfumery",
    authorName: "Élodie Martineau, Master Perfumer",
    author: { firstName: "Élodie", lastName: "Martineau" },
    coverImageUrl: "https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?auto=format&fit=crop&w=1600&q=85",
    isPublished: true,
    publishedAt: "2026-07-28T14:30:00.000Z",
    seoTitle: "Nocturne: 35% Extrait de Parfum Extraction | VELORA Journal",
    seoDescription: "Learn how VELORA compounds rare 35% pure extraits in Grasse using subcritical botanical extraction.",
    ogImage: "https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?auto=format&fit=crop&w=1200&q=85",
    canonicalUrl: "https://velora-ateliers.com/journal/nocturne-dark-art-of-extraction",
    relatedProductIds: ["prod-frg-noir", "prod-frg-oud"],
    content: `In the hills overlooking the Mediterranean, dawn arrives with a cool mist across the terraced fields of Grasse. During these precise pre-dawn hours, Centifolia rose petals and night-blooming jasmine must be hand-harvested before the morning sun evaporates their delicate aromatic compounds.

Most modern fragrance houses dilute perfumes to 12% or 18% concentration. VELORA operates within the realm of High Extrait—formulating exclusively at 30% to 35% concentration.

> "At 35% pure oil concentration, an extrait does not shout. It stays close to the skin with an intimate, velvet trail that endures for twenty-four hours."

## Low-Temperature Extraction

Traditional steam distillation subjects fragile botanical molecules to high temperatures. To prevent this, our laboratory uses gentle fluid extraction at controlled temperatures below 31°C. This allows us to capture the true scent of living blossoms and aged smoked agarwood without heat damage.

The extracted absolute is then left to rest for 120 days in temperature-controlled oak casks, allowing the complex resins to marry harmoniously before being hand-bottled in frosted crystal flacons.`,
  },
  {
    id: "post-3",
    title: "Monochrome & Metallurgy: The DLC Titanium Study",
    slug: "monochrome-and-metallurgy-dlc-titanium",
    subtitle: "Engineering Grade 5 titanium cases with diamond-like carbon physical vapor deposition",
    excerpt: "Combining aerospace lightness with scratch-resistant obsidian aesthetics for the modern collector.",
    category: "Atelier",
    authorName: "Marc Renggli, Materials Director",
    author: { firstName: "Marc", lastName: "Renggli" },
    coverImageUrl: "https://images.unsplash.com/photo-1547996160-71dfabb1d0a5?auto=format&fit=crop&w=1600&q=85",
    isPublished: true,
    publishedAt: "2026-06-12T09:15:00.000Z",
    seoTitle: "Obsidian DLC Titanium Metallurgy | VELORA Journal",
    seoDescription: "An in-depth study into VELORA's aerospace Grade 5 titanium cases treated with Diamond-Like Carbon (DLC).",
    ogImage: "https://images.unsplash.com/photo-1547996160-71dfabb1d0a5?auto=format&fit=crop&w=1200&q=85",
    canonicalUrl: "https://velora-ateliers.com/journal/monochrome-and-metallurgy-dlc-titanium",
    relatedProductIds: ["prod-noir-01", "prod-noir-02"],
    content: `The quest for the ultimate luxury watch case has historically centered upon noble metals: 18k yellow, white, and rose gold. Yet modern watch collectors demand an alloy that delivers high durability alongside light wrist comfort.

Enter Grade 5 Titanium (Ti-6Al-4V). Twice as light as steel yet possessing superior tensile strength, Grade 5 titanium presents exceptional challenges during hand-finishing due to its hardness and low thermal conductivity.

> "Polishing Grade 5 titanium requires specialized ceramic laps and four times the labor of traditional gold, yielding an understated, technical luster."

By applying a microscopic Diamond-Like Carbon (DLC) coating via physical vapor deposition in a high-vacuum chamber, the outer surface achieves a hardness exceeding 3,000 Vickers—rendering the case virtually impervious to scratches and daily wear while maintaining a deep velvet matte black finish.`,
  },
];

export const FALLBACK_HOMEPAGE_SECTIONS = [
  {
    id: "sec-hero",
    sectionKey: "hero_main",
    name: "Hero Section",
    title: "TIME, REFINED.",
    subtitle: "Contemporary timepieces created for moments that matter.",
    content: {
      eyebrow: "VELORA GENEVA & GRASSE",
      ctaText: "Discover The Collection",
      ctaLink: "/collections/signature",
      secondaryCtaText: "Explore Watches",
      secondaryCtaLink: "/watches",
      bgImageUrl: "/images/products/watches/velora-signature-01/editorial.jpg",
    },
    sortOrder: 1,
    isActive: true,
  },
  {
    id: "sec-featured-watch",
    sectionKey: "featured_watch",
    name: "Featured Watch",
    title: "VELORA SIGNATURE 01",
    subtitle: "The Archetype of Precision and Restraint",
    content: {
      productSlug: "velora-signature-01",
      badge: "Flagship Edition",
      description: "Our signature 39mm timepiece crafted in cryogenic-hardened 904L steel with an opaline ivory dial, blued feuille hands, and an in-house automatic movement with 68 hours of power reserve.",
      ctaText: "View Details",
      ctaLink: "/product/velora-signature-01",
    },
    sortOrder: 2,
    isActive: true,
  },
  {
    id: "sec-collection-story",
    sectionKey: "collection_story",
    name: "Collection Story",
    title: "A Study in Restraint",
    subtitle: "Where Mechanical Precision Meets Olfactory Art",
    content: {
      quote: "We believe true luxury is found not in excess, but in the perfection of essential lines.",
      author: "Atelier Philosophy",
      ctaText: "Discover Our Story",
      ctaLink: "/journal/architecture-of-the-free-sprung-balance-wheel",
    },
    sortOrder: 3,
    isActive: true,
  },
  {
    id: "sec-collections-grid",
    sectionKey: "collections_grid",
    name: "Collections Grid",
    title: "The Collections",
    subtitle: "Three Distinct Expressions of Modern Horology",
    content: {
      signatureTitle: "SIGNATURE",
      signatureSubtitle: "Purity of form and mechanical balance",
      noirTitle: "NOIR",
      noirSubtitle: "Shadowed DLC titanium and high-tech ceramic",
      classicTitle: "CLASSIC",
      classicSubtitle: "Porcelain dials and ultra-thin silhouettes",
    },
    sortOrder: 4,
    isActive: true,
  },
  {
    id: "sec-split",
    sectionKey: "watch_fragrance_split",
    name: "Watch & Fragrance Split",
    title: "Two Disciplines. One Maison.",
    subtitle: "Haute Horlogerie in Geneva. High Perfumery in Grasse.",
    content: {
      timeTitle: "Haute Horlogerie",
      timeSubtitle: "Mechanical Complications",
      timeDescription: "Precision movements hand-assembled in Geneva.",
      timeCtaText: "Discover Watches",
      timeCtaLink: "/watches",
      timeImageUrl: "/images/products/watches/velora-signature-01/editorial.jpg",
      fragranceTitle: "High Perfumery",
      fragranceSubtitle: "Pure Extraits de Parfum",
      fragranceDescription: "Botanical extracts distilled at high concentration in Grasse.",
      fragranceCtaText: "Discover Fragrances",
      fragranceCtaLink: "/fragrances",
      fragranceImageUrl: "/images/products/fragrances/velora-noir-extrait/editorial.jpg",
    },
    sortOrder: 5,
    isActive: true,
  },
  {
    id: "sec-signature-product",
    sectionKey: "signature_product",
    name: "Signature Product Spotlight",
    title: "Crafted for Generations",
    subtitle: "VELORA SIGNATURE 01",
    content: {
      productSlug: "velora-signature-01",
      ctaText: "Acquire This Timepiece",
      specs: [
        { label: "Movement", value: "Automatic Calibre VA-01" },
        { label: "Case", value: "39mm 904L Stainless Steel" },
        { label: "Power Reserve", value: "68 Hours" },
        { label: "Crystal", value: "Double-Domed Sapphire" },
      ],
    },
    sortOrder: 6,
    isActive: true,
  },
  {
    id: "sec-craftsmanship",
    sectionKey: "craftsmanship_gallery",
    name: "Craftsmanship Gallery",
    title: "Macro Details",
    subtitle: "Precision Finishings Inspected to the Micron",
    content: {},
    sortOrder: 7,
    isActive: true,
  },
  {
    id: "sec-fragrance-editorial",
    sectionKey: "fragrance_editorial",
    name: "Fragrance Editorial",
    title: "Pure Extraits de Parfum",
    subtitle: "Compounded in Grasse with 30% to 35% Pure Perfume Oil",
    content: {
      highlightFragranceSlug: "velora-noir-extrait",
      ctaText: "Explore High Perfumery",
      ctaLink: "/fragrances",
    },
    sortOrder: 8,
    isActive: true,
  },
  {
    id: "sec-gifting",
    sectionKey: "gifting_packaging",
    name: "Gifting & Packaging",
    title: "The Unboxing Ritual",
    subtitle: "Every creation arrives in handcrafted packaging with an individual certificate of authenticity.",
    content: {
      imageUrl: "/images/products/watches/velora-signature-01/packaging.jpg",
    },
    sortOrder: 9,
    isActive: true,
  },
  {
    id: "sec-brand-story",
    sectionKey: "brand_story",
    name: "Brand Story",
    title: "Heritage & Craft",
    subtitle: "Independent Swiss watchmaking and artisanal French perfumery united under a single standard of excellence.",
    content: {
      ctaText: "Read The Journal",
      ctaLink: "/journal",
    },
    sortOrder: 10,
    isActive: true,
  },
  {
    id: "sec-journal-preview",
    sectionKey: "journal_preview",
    name: "Journal Preview",
    title: "The VELORA Journal",
    subtitle: "Chronicles on mechanical movements, rare botanicals, and modern design.",
    content: {},
    sortOrder: 11,
    isActive: true,
  },
  {
    id: "sec-newsletter",
    sectionKey: "newsletter_section",
    name: "Newsletter Section",
    title: "Join the VELORA Circle",
    subtitle: "Receive private invitations, new edition announcements, and horological insights.",
    content: {},
    sortOrder: 12,
    isActive: true,
  },
];
