import { ProductItem } from "@/types/product";

export interface CatalogCollection {
  id: string;
  name: string;
  slug: string;
  description: string;
  heroImage: string;
  bannerUrl: string;
  featured: boolean;
  isActive: boolean;
  products?: Array<{
    product: ProductItem;
  }>;
  createdAt: string;
  updatedAt: string;
}

export interface CatalogCategory {
  id: string;
  name: string;
  slug: string;
  description: string;
  imageUrl: string;
  ogImage?: string;
  seoTitle?: string;
  seoDescription?: string;
  canonicalUrl?: string;
}

export interface CatalogJournalPost {
  id: string;
  title: string;
  slug: string;
  subtitle: string;
  excerpt: string;
  category: string;
  authorName: string;
  author?: { firstName: string; lastName: string; email?: string };
  coverImageUrl: string;
  isPublished: boolean;
  publishedAt: string;
  seoTitle: string;
  seoDescription: string;
  ogImage: string;
  canonicalUrl: string;
  relatedProductIds: string[];
  content: string;
}

export const FALLBACK_CATEGORIES: CatalogCategory[] = [
  {
    id: "cat-horlogerie",
    name: "Luxury Watches",
    slug: "haute-horlogerie",
    description: "Mechanical timepieces handcrafted with in-house automatic movements, sapphire crystals, and refined proportions.",
    imageUrl: "/images/products/watches/velora-signature-01/editorial.jpg",
    ogImage: "/images/products/watches/velora-signature-01/front.jpg",
    seoTitle: "Luxury Watches in Pakistan | VELORA",
    seoDescription: "Explore luxury automatic and mechanical watches crafted with sapphire crystal and surgical stainless steel in Pakistan.",
    canonicalUrl: "https://velorawatches.pk/watches",
  },
  {
    id: "cat-parfumerie",
    name: "Luxury Fragrances",
    slug: "high-perfumery",
    description: "Pure concentrated perfumes crafted with rare aged woods, rich resins, and long-lasting floral essences in crystal bottles.",
    imageUrl: "/images/products/fragrances/velora-noir-extrait/editorial.jpg",
    ogImage: "/images/products/fragrances/velora-noir-extrait/bottle-front.jpg",
    seoTitle: "Luxury Perfumes in Pakistan | VELORA",
    seoDescription: "Discover pure concentrated perfumes crafted with rare aged agarwood, rich amber, and lasting floral oils.",
    canonicalUrl: "https://velorawatches.pk/fragrances",
  },
];

export const FALLBACK_COLLECTIONS: CatalogCollection[] = [
  {
    id: "col-signature",
    name: "Signature Collection",
    slug: "signature",
    description: "Our core archetype of modern watch design, clean lines, and balanced mechanics.",
    heroImage: "/images/products/watches/velora-signature-01/editorial.jpg",
    bannerUrl: "/images/products/watches/velora-signature-01/editorial.jpg",
    featured: true,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "col-noir",
    name: "Noir Black Collection",
    slug: "noir",
    description: "Bold monochromatic watches forged in black-coated titanium and high-density ceramic.",
    heroImage: "/images/products/watches/velora-noir-01/editorial.jpg",
    bannerUrl: "/images/products/watches/velora-noir-01/editorial.jpg",
    featured: true,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "col-classic",
    name: "Classic Heritage Collection",
    slug: "classic",
    description: "Enduring proportions, porcelain white dials, and slender dress watches designed for formal occasions.",
    heroImage: "/images/products/watches/velora-classic-01/editorial.jpg",
    bannerUrl: "/images/products/watches/velora-classic-01/editorial.jpg",
    featured: true,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "col-celestial",
    name: "Celestial Collection",
    slug: "celestial-complications",
    description: "Timepieces inspired by astronomical geometry and complex mechanical displays.",
    heroImage: "/images/products/watches/velora-signature-02/editorial.jpg",
    bannerUrl: "/images/products/watches/velora-signature-02/editorial.jpg",
    featured: true,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "col-nocturne",
    name: "Nocturne Evening Collection",
    slug: "nocturne-prive",
    description: "Deep, intimate perfumes formulated with high concentration for evening wear and special gatherings.",
    heroImage: "/images/products/fragrances/velora-noir-extrait/lifestyle.jpg",
    bannerUrl: "/images/products/fragrances/velora-noir-extrait/lifestyle.jpg",
    featured: true,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
];

export const FALLBACK_PRODUCTS: ProductItem[] = [
  // 1. VELORA SIGNATURE 01
  {
    id: "prod-sig-01",
    name: "VELORA SIGNATURE 01",
    slug: "velora-signature-01",
    sku: "VEL-SIG-01",
    shortDescription: "Original 39mm automatic watch in surgical 904L steel, warm ivory dial, heat-blued hands, and saddle-stitched calfskin leather.",
    description: "The VELORA SIGNATURE 01 is our flagship timepiece. Designed with perfect symmetry, the 39mm case is crafted from hardened 904L stainless steel, alternating between mirror-polished bevels and fine brushed flanks. The scratch-resistant double-domed sapphire crystal features anti-reflective coating, protecting an opaline ivory dial. Applied gold baton hour markers catch the light, while heat-blued steel hands trace time powered by our in-house automatic calibre with 68 hours of power reserve.",
    price: 65000,
    compareAtPrice: 75000,
    cost: 25000,
    status: "PUBLISHED",
    featured: true,
    tags: ["Automatic", "Sapphire", "904L Steel", "Signature", "Iconic", "In-House"],
    movement: "In-House Calibre VA-01 Automatic (28,800 vph)",
    powerReserve: "68 Hours",
    caseMaterial: "Cryogenic-Hardened 904L Stainless Steel",
    caseDiameter: "39.0 mm",
    caseThickness: "9.2 mm",
    crystal: "Double-Domed Sapphire with 5x Anti-Reflective Coating",
    waterResistance: "50m / 5 ATM",
    dialColor: "Warm Opaline Ivory with Rose Gold Markers",
    strapMaterial: "Cognac Full-Grain Calfskin, Hand-Stitched",
    clasp: "Custom Micro-Adjustable 904L Steel Folding Clasp",
    seoTitle: "VELORA SIGNATURE 01 | Automatic 39mm in 904L Steel",
    seoDescription: "The flagship VELORA SIGNATURE 01 automatic timepiece. In-house automatic movement, 904L steel, double-domed sapphire, and ivory dial.",
    category: { id: "cat-horlogerie", name: "Luxury Watches", slug: "haute-horlogerie" },
    collections: [
      { collection: { id: "col-signature", name: "Signature Collection", slug: "signature", bannerUrl: "/images/products/watches/velora-signature-01/editorial.jpg" } },
      { collection: { id: "col-classic", name: "Classic Heritage Collection", slug: "classic", bannerUrl: "/images/products/watches/velora-classic-01/editorial.jpg" } },
    ],
    inventory: { quantity: 12, warehouseLocation: "Lahore Central Vault" },
    images: [
      { id: "sig01-img-1", url: "/images/products/watches/velora-signature-01/front.jpg", altText: "VELORA SIGNATURE 01 Front Dial View", sortOrder: 1, isPrimary: true },
      { id: "sig01-img-2", url: "/images/products/watches/velora-signature-01/angle.jpg", altText: "VELORA SIGNATURE 01 45-Degree Angle", sortOrder: 2, isPrimary: false },
      { id: "sig01-img-3", url: "/images/products/watches/velora-signature-01/side.jpg", altText: "VELORA SIGNATURE 01 Side Profile", sortOrder: 3, isPrimary: false },
      { id: "sig01-img-4", url: "/images/products/watches/velora-signature-01/dial-macro.jpg", altText: "VELORA SIGNATURE 01 Opaline Dial Close-Up", sortOrder: 4, isPrimary: false },
      { id: "sig01-img-5", url: "/images/products/watches/velora-signature-01/crown-macro.jpg", altText: "VELORA SIGNATURE 01 Winding Crown Close-Up", sortOrder: 5, isPrimary: false },
      { id: "sig01-img-6", url: "/images/products/watches/velora-signature-01/case-macro.jpg", altText: "VELORA SIGNATURE 01 Steel Case Chamfer", sortOrder: 6, isPrimary: false },
      { id: "sig01-img-7", url: "/images/products/watches/velora-signature-01/strap-clasp.jpg", altText: "VELORA SIGNATURE 01 Leather Strap & Clasp", sortOrder: 7, isPrimary: false },
      { id: "sig01-img-8", url: "/images/products/watches/velora-signature-01/wrist-lifestyle.jpg", altText: "VELORA SIGNATURE 01 On Wrist", sortOrder: 8, isPrimary: false },
      { id: "sig01-img-9", url: "/images/products/watches/velora-signature-01/editorial.jpg", altText: "VELORA SIGNATURE 01 Editorial Shot", sortOrder: 9, isPrimary: false },
      { id: "sig01-img-10", url: "/images/products/watches/velora-signature-01/packaging.jpg", altText: "VELORA SIGNATURE 01 Luxury Wooden Presentation Box", sortOrder: 10, isPrimary: false },
    ],
    variants: [
      { id: "sig01-v1", sku: "VEL-SIG-01-COG", title: "Cognac Calfskin Leather Strap", price: 65000, stock: 12, attributes: { strap: "Cognac Leather", buckle: "Folding Clasp" } },
      { id: "sig01-v2", sku: "VEL-SIG-01-NOIR", title: "Midnight Black Textured Strap", price: 68000, stock: 8, attributes: { strap: "Midnight Black", buckle: "Folding Clasp" } },
    ],
    macroDetails: [
      { part: "dial", title: "The Opaline Ivory Dial", subtitle: "Fine Micro-Texture & Gold Markers", description: "Subtle velvet ivory dial surface with applied diamond-cut gold baton indices.", imageUrl: "/images/products/watches/velora-signature-01/dial-macro.jpg" },
      { part: "hands", title: "The Leaf Hands", subtitle: "Heat-Blued Tempered Steel", description: "Heat-tempered blued steel leaf hands balanced to sub-milligram tolerances.", imageUrl: "/images/products/watches/velora-signature-01/front.jpg" },
      { part: "crown", title: "The Knurled Crown", subtitle: "Dual-Gasket Protection", description: "Precision-fluted winding crown engineered with dual internal O-rings for smooth tactile winding.", imageUrl: "/images/products/watches/velora-signature-01/crown-macro.jpg" },
      { part: "case", title: "The 904L Steel Case", subtitle: "Satin Brush & Mirror Bevels", description: "Hardened 904L steel with hand-polished chamfers contrasting smooth satin sides.", imageUrl: "/images/products/watches/velora-signature-01/case-macro.jpg" },
      { part: "strap", title: "Hand-Stitched Leather", subtitle: "Full-Grain Leather", description: "Full-grain vegetable-tanned calfskin hand-stitched with waxed linen thread.", imageUrl: "/images/products/watches/velora-signature-01/strap-clasp.jpg" },
      { part: "clasp", title: "Micro-Adjustable Clasp", subtitle: "Solid Steel Folding Mechanism", description: "Folding clasp providing instant tool-free micro-adjustment for comfort.", imageUrl: "/images/products/watches/velora-signature-01/strap-clasp.jpg" },
    ],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // 2. VELORA SIGNATURE 02
  {
    id: "prod-sig-02",
    name: "VELORA SIGNATURE 02",
    slug: "velora-signature-02",
    sku: "VEL-SIG-02",
    shortDescription: "39mm 18K Rose Gold plated case framing a charcoal sunburst dial with hand-applied gold markers and slate leather.",
    description: "An evening evolution of our signature silhouette. Featuring a warm 18K Rose Gold finish, the SIGNATURE 02 pairs architectural warmth with a sunburst charcoal dial that darkens toward the edges. The sapphire exhibition back reveals our automatic movement with circular striped decoration and a skeletonized gold rotor.",
    price: 85000,
    compareAtPrice: 95000,
    cost: 32000,
    status: "PUBLISHED",
    featured: true,
    tags: ["Automatic", "Rose Gold", "Sunburst Dial", "Signature", "Limited Run"],
    movement: "In-House Calibre VA-01G Rose Gold Automatic (28,800 vph)",
    powerReserve: "68 Hours",
    caseMaterial: "Solid 18K Rose Gold Finish on 316L Steel",
    caseDiameter: "39.0 mm",
    caseThickness: "9.2 mm",
    crystal: "Double-Domed Sapphire with Internal Anti-Reflective Treatment",
    waterResistance: "50m / 5 ATM",
    dialColor: "Smoked Slate Charcoal Sunburst",
    strapMaterial: "Hand-Cut Matte Slate Alligator-Grain Leather",
    clasp: "Rose Gold Folding Clasp",
    seoTitle: "VELORA SIGNATURE 02 | 18K Rose Gold Luxury Watch",
    seoDescription: "18K Rose Gold finish case, smoked charcoal sunburst dial, and automatic movement with 68 hours reserve.",
    category: { id: "cat-horlogerie", name: "Luxury Watches", slug: "haute-horlogerie" },
    collections: [
      { collection: { id: "col-signature", name: "Signature Collection", slug: "signature", bannerUrl: "/images/products/watches/velora-signature-02/editorial.jpg" } },
      { collection: { id: "col-celestial", name: "Celestial Collection", slug: "celestial-complications", bannerUrl: "/images/products/watches/velora-signature-02/editorial.jpg" } },
    ],
    inventory: { quantity: 9, warehouseLocation: "Karachi Central Vault" },
    images: [
      { id: "sig02-img-1", url: "/images/products/watches/velora-signature-02/front.jpg", altText: "VELORA SIGNATURE 02 Front View", sortOrder: 1, isPrimary: true },
      { id: "sig02-img-2", url: "/images/products/watches/velora-signature-02/angle.jpg", altText: "VELORA SIGNATURE 02 Rose Gold Angle", sortOrder: 2, isPrimary: false },
      { id: "sig02-img-3", url: "/images/products/watches/velora-signature-02/side.jpg", altText: "VELORA SIGNATURE 02 Side Profile", sortOrder: 3, isPrimary: false },
      { id: "sig02-img-4", url: "/images/products/watches/velora-signature-02/dial-macro.jpg", altText: "VELORA SIGNATURE 02 Sunburst Dial Detail", sortOrder: 4, isPrimary: false },
      { id: "sig02-img-5", url: "/images/products/watches/velora-signature-02/crown-macro.jpg", altText: "VELORA SIGNATURE 02 Rose Gold Crown", sortOrder: 5, isPrimary: false },
      { id: "sig02-img-6", url: "/images/products/watches/velora-signature-02/case-macro.jpg", altText: "VELORA SIGNATURE 02 Polished Bevels", sortOrder: 6, isPrimary: false },
      { id: "sig02-img-7", url: "/images/products/watches/velora-signature-02/strap-clasp.jpg", altText: "VELORA SIGNATURE 02 Slate Strap & Clasp", sortOrder: 7, isPrimary: false },
      { id: "sig02-img-8", url: "/images/products/watches/velora-signature-02/wrist-lifestyle.jpg", altText: "VELORA SIGNATURE 02 On Wrist Evening Wear", sortOrder: 8, isPrimary: false },
      { id: "sig02-img-9", url: "/images/products/watches/velora-signature-02/editorial.jpg", altText: "VELORA SIGNATURE 02 Editorial Campaign", sortOrder: 9, isPrimary: false },
      { id: "sig02-img-10", url: "/images/products/watches/velora-signature-02/packaging.jpg", altText: "VELORA SIGNATURE 02 Wooden Presentation Box", sortOrder: 10, isPrimary: false },
    ],
    variants: [
      { id: "sig02-v1", sku: "VEL-SIG-02-SLT", title: "Matte Slate Leather Strap", price: 85000, stock: 5, attributes: { strap: "Matte Slate Leather", buckle: "Rose Gold Clasp" } },
      { id: "sig02-v2", sku: "VEL-SIG-02-BRN", title: "Espresso Brown Leather Strap", price: 85000, stock: 4, attributes: { strap: "Espresso Brown Leather", buckle: "Rose Gold Clasp" } },
    ],
    macroDetails: [
      { part: "dial", title: "The Smoked Charcoal Dial", subtitle: "Sunburst Gradient", description: "Radial metallic brushing that deepens toward the outer minute track.", imageUrl: "/images/products/watches/velora-signature-02/dial-macro.jpg" },
      { part: "hands", title: "Gold Faceted Hands", subtitle: "Polished Bevels", description: "Solid rose gold hands chamfered along each facet edge for crisp legibility.", imageUrl: "/images/products/watches/velora-signature-02/front.jpg" },
      { part: "crown", title: "The Fluted Crown", subtitle: "Smooth Winding", description: "Fluted rose gold crown offering silky winding resistance.", imageUrl: "/images/products/watches/velora-signature-02/crown-macro.jpg" },
      { part: "case", title: "Rose Gold Finish Case", subtitle: "Warm Alloy", description: "Long-lasting rose gold finish resisting fading and scratches.", imageUrl: "/images/products/watches/velora-signature-02/case-macro.jpg" },
      { part: "strap", title: "Matte Slate Leather", subtitle: "Hand-Crafted", description: "Hand-selected leather strap finished with seamless rolled edges.", imageUrl: "/images/products/watches/velora-signature-02/strap-clasp.jpg" },
      { part: "clasp", title: "Rose Gold Clasp", subtitle: "Comfort Fit", description: "Folding clasp contoured precisely to wrist curvature.", imageUrl: "/images/products/watches/velora-signature-02/strap-clasp.jpg" },
    ],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // 3. VELORA NOIR 01
  {
    id: "prod-noir-01",
    name: "VELORA NOIR 01",
    slug: "velora-noir-01",
    sku: "VEL-NOIR-01",
    shortDescription: "40mm Grade 5 DLC Titanium watch with light-absorbing velvet black dial and dark gunmetal accents.",
    description: "Built from Grade 5 Titanium and protected with diamond-like carbon coating, the VELORA NOIR 01 represents modern stealth luxury. The dial features an ultra-matte velvet black surface that absorbs reflections, contrasted against polished gunmetal indexes and luminescent hour pointers. Paired with a textured vulcanized rubber strap engineered for all climates.",
    price: 72000,
    compareAtPrice: 82000,
    cost: 28000,
    status: "PUBLISHED",
    featured: true,
    tags: ["Titanium", "DLC Coating", "Noir", "Stealth Luxury", "Automatic"],
    movement: "In-House Calibre VA-02T DLC Automatic",
    powerReserve: "72 Hours",
    caseMaterial: "Grade 5 Titanium with Diamond-Like Carbon (DLC)",
    caseDiameter: "40.0 mm",
    caseThickness: "9.6 mm",
    crystal: "Curved Sapphire Crystal with Dual Anti-Glare Treatment",
    waterResistance: "100m / 10 ATM",
    dialColor: "Ultra-Matte Velvet Black with Gunmetal Markers",
    strapMaterial: "Textured High-Performance Rubber",
    clasp: "Black Titanium Safety Folding Clasp",
    seoTitle: "VELORA NOIR 01 | DLC Titanium Automatic Watch",
    seoDescription: "Grade 5 Titanium in black DLC coating. Velvet black dial with 72h power reserve.",
    category: { id: "cat-horlogerie", name: "Luxury Watches", slug: "haute-horlogerie" },
    collections: [
      { collection: { id: "col-noir", name: "Noir Black Collection", slug: "noir", bannerUrl: "/images/products/watches/velora-noir-01/editorial.jpg" } },
    ],
    inventory: { quantity: 16, warehouseLocation: "Lahore Central Vault" },
    images: [
      { id: "noir01-img-1", url: "/images/products/watches/velora-noir-01/front.jpg", altText: "VELORA NOIR 01 Studio Front View", sortOrder: 1, isPrimary: true },
      { id: "noir01-img-2", url: "/images/products/watches/velora-noir-01/angle.jpg", altText: "VELORA NOIR 01 Black Titanium Angle", sortOrder: 2, isPrimary: false },
      { id: "noir01-img-3", url: "/images/products/watches/velora-noir-01/side.jpg", altText: "VELORA NOIR 01 Matte Black Profile", sortOrder: 3, isPrimary: false },
      { id: "noir01-img-4", url: "/images/products/watches/velora-noir-01/dial-macro.jpg", altText: "VELORA NOIR 01 Black Dial Texture", sortOrder: 4, isPrimary: false },
      { id: "noir01-img-5", url: "/images/products/watches/velora-noir-01/crown-macro.jpg", altText: "VELORA NOIR 01 Knurled Black Crown", sortOrder: 5, isPrimary: false },
      { id: "noir01-img-6", url: "/images/products/watches/velora-noir-01/case-macro.jpg", altText: "VELORA NOIR 01 Titanium Case Detail", sortOrder: 6, isPrimary: false },
      { id: "noir01-img-7", url: "/images/products/watches/velora-noir-01/strap-clasp.jpg", altText: "VELORA NOIR 01 Rubber Strap & Clasp", sortOrder: 7, isPrimary: false },
      { id: "noir01-img-8", url: "/images/products/watches/velora-noir-01/wrist-lifestyle.jpg", altText: "VELORA NOIR 01 On Wrist", sortOrder: 8, isPrimary: false },
      { id: "noir01-img-9", url: "/images/products/watches/velora-noir-01/editorial.jpg", altText: "VELORA NOIR 01 Editorial Campaign", sortOrder: 9, isPrimary: false },
      { id: "noir01-img-10", url: "/images/products/watches/velora-noir-01/packaging.jpg", altText: "VELORA NOIR 01 Black Presentation Box", sortOrder: 10, isPrimary: false },
    ],
    variants: [
      { id: "noir01-v1", sku: "VEL-NOIR-01-FKM", title: "Textured Black Rubber Strap", price: 72000, stock: 10, attributes: { strap: "Black Rubber", buckle: "Black Deployant" } },
      { id: "noir01-v2", sku: "VEL-NOIR-01-ALC", title: "Black Suede Technical Strap", price: 75000, stock: 6, attributes: { strap: "Black Technical Suede", buckle: "Black Deployant" } },
    ],
    macroDetails: [
      { part: "dial", title: "The Velvet Black Dial", subtitle: "Light-Absorbing Surface", description: "Specialized coating creating high-contrast depth against gunmetal markers.", imageUrl: "/images/products/watches/velora-noir-01/dial-macro.jpg" },
      { part: "hands", title: "Dark Gunmetal Hands", subtitle: "Luminescent Inlay", description: "Deep gunmetal hands inlaid with luminous pigment for night visibility.", imageUrl: "/images/products/watches/velora-noir-01/front.jpg" },
      { part: "crown", title: "Stealth Screw-Down Crown", subtitle: "100m Water Resistance", description: "Tactile knurled titanium crown coated in black DLC with double O-ring seal.", imageUrl: "/images/products/watches/velora-noir-01/crown-macro.jpg" },
      { part: "case", title: "Grade 5 Titanium", subtitle: "Lightweight Strength", description: "Weighs only 64 grams while offering extraordinary tensile strength and scratch immunity.", imageUrl: "/images/products/watches/velora-noir-01/case-macro.jpg" },
      { part: "strap", title: "Textured Rubber", subtitle: "Sweat & Water Resistant", description: "Geometric underside channels airflow for comfortable all-day wear.", imageUrl: "/images/products/watches/velora-noir-01/strap-clasp.jpg" },
      { part: "clasp", title: "Black Safety Clasp", subtitle: "Push-Button Release", description: "Precision titanium mechanism locking securely with satisfying click feedback.", imageUrl: "/images/products/watches/velora-noir-01/strap-clasp.jpg" },
    ],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // 4. VELORA NOIR 02
  {
    id: "prod-noir-02",
    name: "VELORA NOIR 02",
    slug: "velora-noir-02",
    sku: "VEL-NOIR-02",
    shortDescription: "Openworked skeleton watch in black scratch-proof ceramic with smoked sapphire dial and crimson seconds hand.",
    description: "A striking celebration of mechanical movement. The NOIR 02 reveals the skeletonized gear train through a smoked sapphire dial. Encased in high-density black zirconium ceramic that never scratches, with floating dark hour markers and an eye-catching crimson seconds pointer.",
    price: 115000,
    compareAtPrice: 130000,
    cost: 45000,
    status: "PUBLISHED",
    featured: true,
    tags: ["Skeleton", "Ceramic", "High Horology", "Noir", "Openworked"],
    movement: "Calibre VA-SKEL Openworked Skeleton Movement",
    powerReserve: "70 Hours",
    caseMaterial: "High-Tech Black Zirconium Ceramic",
    caseDiameter: "41.0 mm",
    caseThickness: "10.1 mm",
    crystal: "Scratch-Proof Flat Sapphire Crystal Front & Back",
    waterResistance: "50m / 5 ATM",
    dialColor: "Openworked Smoked Sapphire with Crimson Accent",
    strapMaterial: "Ballistic Weave Technical Rubber with Leather Lining",
    clasp: "Ceramic & Titanium Dual Deployant",
    seoTitle: "VELORA NOIR 02 | High-Tech Ceramic Skeleton Watch",
    seoDescription: "Black zirconium ceramic case housing skeletonized mechanical movement with smoked sapphire crystal.",
    category: { id: "cat-horlogerie", name: "Luxury Watches", slug: "haute-horlogerie" },
    collections: [
      { collection: { id: "col-noir", name: "Noir Black Collection", slug: "noir", bannerUrl: "/images/products/watches/velora-noir-02/editorial.jpg" } },
    ],
    inventory: { quantity: 7, warehouseLocation: "Islamabad Central Vault" },
    images: [
      { id: "noir02-img-1", url: "/images/products/watches/velora-noir-02/front.jpg", altText: "VELORA NOIR 02 Front View", sortOrder: 1, isPrimary: true },
      { id: "noir02-img-2", url: "/images/products/watches/velora-noir-02/angle.jpg", altText: "VELORA NOIR 02 Ceramic Angle", sortOrder: 2, isPrimary: false },
      { id: "noir02-img-3", url: "/images/products/watches/velora-noir-02/side.jpg", altText: "VELORA NOIR 02 Side Profile", sortOrder: 3, isPrimary: false },
      { id: "noir02-img-4", url: "/images/products/watches/velora-noir-02/dial-macro.jpg", altText: "VELORA NOIR 02 Skeleton Gear Close-Up", sortOrder: 4, isPrimary: false },
      { id: "noir02-img-5", url: "/images/products/watches/velora-noir-02/crown-macro.jpg", altText: "VELORA NOIR 02 Black Ceramic Crown", sortOrder: 5, isPrimary: false },
      { id: "noir02-img-6", url: "/images/products/watches/velora-noir-02/case-macro.jpg", altText: "VELORA NOIR 02 Ceramic Case Detail", sortOrder: 6, isPrimary: false },
      { id: "noir02-img-7", url: "/images/products/watches/velora-noir-02/strap-clasp.jpg", altText: "VELORA NOIR 02 Strap & Clasp", sortOrder: 7, isPrimary: false },
      { id: "noir02-img-8", url: "/images/products/watches/velora-noir-02/wrist-lifestyle.jpg", altText: "VELORA NOIR 02 On Wrist", sortOrder: 8, isPrimary: false },
      { id: "noir02-img-9", url: "/images/products/watches/velora-noir-02/editorial.jpg", altText: "VELORA NOIR 02 Editorial Campaign", sortOrder: 9, isPrimary: false },
      { id: "noir02-img-10", url: "/images/products/watches/velora-noir-02/packaging.jpg", altText: "VELORA NOIR 02 Presentation Box", sortOrder: 10, isPrimary: false },
    ],
    variants: [
      { id: "noir02-v1", sku: "VEL-NOIR-02-BAL", title: "Ballistic Weave Rubber Strap", price: 115000, stock: 4, attributes: { strap: "Ballistic Weave", buckle: "Ceramic Clasp" } },
      { id: "noir02-v2", sku: "VEL-NOIR-02-CER", title: "Full Matte Ceramic Link Bracelet", price: 135000, stock: 3, attributes: { strap: "Matte Ceramic Bracelet", buckle: "Titanium Clasp" } },
    ],
    macroDetails: [
      { part: "dial", title: "The Skeleton Movement", subtitle: "Exposed Gear Train", description: "Internal balance wheel, gear train, and spring barrel visible through smoked sapphire.", imageUrl: "/images/products/watches/velora-noir-02/dial-macro.jpg" },
      { part: "hands", title: "Openworked Hands", subtitle: "Crimson Seconds Pointer", description: "Geometric cutout hands counterbalanced with a bright red seconds needle.", imageUrl: "/images/products/watches/velora-noir-02/front.jpg" },
      { part: "crown", title: "Ceramic Crown", subtitle: "Smooth Grip", description: "High-density ceramic crown with integrated rubber grip ring.", imageUrl: "/images/products/watches/velora-noir-02/crown-macro.jpg" },
      { part: "case", title: "Zirconium Ceramic", subtitle: "Scratch-Proof Case", description: "Sintered at high temperature for diamond-level scratch resistance.", imageUrl: "/images/products/watches/velora-noir-02/case-macro.jpg" },
      { part: "strap", title: "Technical Textile", subtitle: "Water Resistant", description: "Durable technical weave exterior with soft leather backing against the wrist.", imageUrl: "/images/products/watches/velora-noir-02/strap-clasp.jpg" },
      { part: "clasp", title: "Ceramic Deployant", subtitle: "Secure Double Fold", description: "High-strength mechanism capped in matching matte black ceramic.", imageUrl: "/images/products/watches/velora-noir-02/strap-clasp.jpg" },
    ],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // 5. VELORA CLASSIC 01
  {
    id: "prod-cls-01",
    name: "VELORA CLASSIC 01",
    slug: "velora-classic-01",
    sku: "VEL-CLS-01",
    shortDescription: "Ultra-slim 38mm dress watch in polished 316L steel with porcelain white dial, Roman numerals, and blued hands.",
    description: "Classic proportions designed for formal attire. Measuring only 7.9mm thick, the VELORA CLASSIC 01 slips effortlessly beneath a shirt cuff. Its glossy porcelain white dial is decorated with slender serif Roman numerals and heat-treated blued steel leaf hands. Powered by a manual-wind movement with 60 hours of smooth winding reserve.",
    price: 55000,
    compareAtPrice: 62000,
    cost: 21000,
    status: "PUBLISHED",
    featured: true,
    tags: ["Manual-Wind", "Ultra-Slim", "Porcelain Dial", "Classic", "Dress Watch"],
    movement: "In-House Calibre VA-03M Manual-Wind Ultra-Thin",
    powerReserve: "60 Hours",
    caseMaterial: "Mirror-Polished 316L Surgical Stainless Steel",
    caseDiameter: "38.0 mm",
    caseThickness: "7.9 mm",
    crystal: "Box-Domed Sapphire Crystal with Anti-Reflective Coating",
    waterResistance: "30m / 3 ATM",
    dialColor: "Porcelain White Multi-Layer Lacquer",
    strapMaterial: "Full-Grain Cognac Brown Leather",
    clasp: "Polished Stainless Steel Pin Buckle",
    seoTitle: "VELORA CLASSIC 01 | Ultra-Thin 38mm Dress Watch",
    seoDescription: "Ultra-slim 7.9mm manual-wind watch with porcelain white dial, Roman numerals, and blued leaf hands.",
    category: { id: "cat-horlogerie", name: "Luxury Watches", slug: "haute-horlogerie" },
    collections: [
      { collection: { id: "col-classic", name: "Classic Heritage Collection", slug: "classic", bannerUrl: "/images/products/watches/velora-classic-01/editorial.jpg" } },
    ],
    inventory: { quantity: 16, warehouseLocation: "Lahore Central Vault" },
    images: [
      { id: "cls01-img-1", url: "/images/products/watches/velora-classic-01/front.jpg", altText: "VELORA CLASSIC 01 Porcelain Dial", sortOrder: 1, isPrimary: true },
      { id: "cls01-img-2", url: "/images/products/watches/velora-classic-01/angle.jpg", altText: "VELORA CLASSIC 01 Formal Angle", sortOrder: 2, isPrimary: false },
      { id: "cls01-img-3", url: "/images/products/watches/velora-classic-01/side.jpg", altText: "VELORA CLASSIC 01 7.9mm Thin Side View", sortOrder: 3, isPrimary: false },
      { id: "cls01-img-4", url: "/images/products/watches/velora-classic-01/dial-macro.jpg", altText: "VELORA CLASSIC 01 Dial Close-Up", sortOrder: 4, isPrimary: false },
      { id: "cls01-img-5", url: "/images/products/watches/velora-classic-01/crown-macro.jpg", altText: "VELORA CLASSIC 01 Slim Crown", sortOrder: 5, isPrimary: false },
      { id: "cls01-img-6", url: "/images/products/watches/velora-classic-01/case-macro.jpg", altText: "VELORA CLASSIC 01 Polished Bezel Detail", sortOrder: 6, isPrimary: false },
      { id: "cls01-img-7", url: "/images/products/watches/velora-classic-01/strap-clasp.jpg", altText: "VELORA CLASSIC 01 Leather Strap & Buckle", sortOrder: 7, isPrimary: false },
      { id: "cls01-img-8", url: "/images/products/watches/velora-classic-01/wrist-lifestyle.jpg", altText: "VELORA CLASSIC 01 On Wrist Formal Wear", sortOrder: 8, isPrimary: false },
      { id: "cls01-img-9", url: "/images/products/watches/velora-classic-01/editorial.jpg", altText: "VELORA CLASSIC 01 Editorial Campaign", sortOrder: 9, isPrimary: false },
      { id: "cls01-img-10", url: "/images/products/watches/velora-classic-01/packaging.jpg", altText: "VELORA CLASSIC 01 Luxury Presentation Case", sortOrder: 10, isPrimary: false },
    ],
    variants: [
      { id: "cls01-v1", sku: "VEL-CLS-01-COG", title: "Cognac Brown Leather Strap", price: 55000, stock: 9, attributes: { strap: "Cognac Leather", buckle: "Pin Buckle" } },
      { id: "cls01-v2", sku: "VEL-CLS-01-NOIR", title: "Black Formal Leather Strap", price: 55000, stock: 7, attributes: { strap: "Black Leather", buckle: "Pin Buckle" } },
    ],
    macroDetails: [
      { part: "dial", title: "The Porcelain White Dial", subtitle: "Glossy Enamel Luster", description: "Seven-layer cold lacquer surface polished by hand to a glassy porcelain finish.", imageUrl: "/images/products/watches/velora-classic-01/dial-macro.jpg" },
      { part: "hands", title: "Tempered Leaf Hands", subtitle: "Thermal Blued Steel", description: "Graceful leaf hands thermally treated to a deep royal blue for lasting beauty.", imageUrl: "/images/products/watches/velora-classic-01/front.jpg" },
      { part: "crown", title: "The Slim Crown", subtitle: "Easy Daily Winding", description: "Classic winding crown providing smooth engagement for your daily winding routine.", imageUrl: "/images/products/watches/velora-classic-01/crown-macro.jpg" },
      { part: "case", title: "Ultra-Thin 7.9mm Profile", subtitle: "Flush Fit", description: "Stepped case profile designed to sit flat and flush against the wrist.", imageUrl: "/images/products/watches/velora-classic-01/case-macro.jpg" },
      { part: "strap", title: "Full-Grain Leather", subtitle: "Handcrafted Longevity", description: "Naturally tanned leather praised for its smooth non-creasing surface.", imageUrl: "/images/products/watches/velora-classic-01/strap-clasp.jpg" },
      { part: "clasp", title: "Engraved Pin Buckle", subtitle: "Understated Elegance", description: "Slender stainless steel buckle engraved with the VELORA insignia.", imageUrl: "/images/products/watches/velora-classic-01/strap-clasp.jpg" },
    ],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // 6. VELORA AUREL 01
  {
    id: "prod-aur-01",
    name: "VELORA AUREL 01",
    slug: "velora-aurel-01",
    sku: "VEL-AUR-01",
    shortDescription: "39.5mm luxury watch in 18K Champagne Gold finish with integrated brick-link bracelet and warm satin dial.",
    description: "Radiant, sculptural, and distinguished. Finished in warm 18K Champagne Gold, the AUREL 01 features a seamless integrated brick-link metal bracelet that drapes comfortably around the wrist. The vertical satin-brushed champagne dial is elevated by gold hour markers and polished sword hands powered by our automatic movement.",
    price: 145000,
    compareAtPrice: 165000,
    cost: 55000,
    status: "PUBLISHED",
    featured: true,
    tags: ["Champagne Gold", "Integrated Bracelet", "Luxury Watches", "Jewelry Watch"],
    movement: "In-House Calibre VA-04 Automatic",
    powerReserve: "65 Hours",
    caseMaterial: "18K Champagne Gold Finish on Surgical Steel",
    caseDiameter: "39.5 mm",
    caseThickness: "8.8 mm",
    crystal: "Double-Domed Scratch-Proof Sapphire Crystal",
    waterResistance: "50m / 5 ATM",
    dialColor: "Vertical Satin Champagne Gold with Baguette Indexes",
    strapMaterial: "Solid Champagne Gold Finish Integrated Brick-Link Bracelet",
    clasp: "Concealed Butterfly Clasp",
    seoTitle: "VELORA AUREL 01 | 18K Champagne Gold Luxury Watch",
    seoDescription: "Champagne gold watch with integrated articulated bracelet and automatic movement.",
    category: { id: "cat-horlogerie", name: "Luxury Watches", slug: "haute-horlogerie" },
    collections: [
      { collection: { id: "col-signature", name: "Signature Collection", slug: "signature", bannerUrl: "/images/products/watches/velora-aurel-01/editorial.jpg" } },
      { collection: { id: "col-classic", name: "Classic Heritage Collection", slug: "classic", bannerUrl: "/images/products/watches/velora-classic-01/editorial.jpg" } },
    ],
    inventory: { quantity: 7, warehouseLocation: "Lahore Central Vault" },
    images: [
      { id: "aur01-img-1", url: "/images/products/watches/velora-aurel-01/front.jpg", altText: "VELORA AUREL 01 Front View", sortOrder: 1, isPrimary: true },
      { id: "aur01-img-2", url: "/images/products/watches/velora-aurel-01/angle.jpg", altText: "VELORA AUREL 01 Integrated Bracelet Angle", sortOrder: 2, isPrimary: false },
      { id: "aur01-img-3", url: "/images/products/watches/velora-aurel-01/side.jpg", altText: "VELORA AUREL 01 8.8mm Slender Profile", sortOrder: 3, isPrimary: false },
      { id: "aur01-img-4", url: "/images/products/watches/velora-aurel-01/dial-macro.jpg", altText: "VELORA AUREL 01 Satin Champagne Dial Close-Up", sortOrder: 4, isPrimary: false },
      { id: "aur01-img-5", url: "/images/products/watches/velora-aurel-01/crown-macro.jpg", altText: "VELORA AUREL 01 Onyx Cabochon Crown", sortOrder: 5, isPrimary: false },
      { id: "aur01-img-6", url: "/images/products/watches/velora-aurel-01/case-macro.jpg", altText: "VELORA AUREL 01 Case Polishing", sortOrder: 6, isPrimary: false },
      { id: "aur01-img-7", url: "/images/products/watches/velora-aurel-01/strap-clasp.jpg", altText: "VELORA AUREL 01 Brick-Link Bracelet & Invisible Clasp", sortOrder: 7, isPrimary: false },
      { id: "aur01-img-8", url: "/images/products/watches/velora-aurel-01/wrist-lifestyle.jpg", altText: "VELORA AUREL 01 On Wrist", sortOrder: 8, isPrimary: false },
      { id: "aur01-img-9", url: "/images/products/watches/velora-aurel-01/editorial.jpg", altText: "VELORA AUREL 01 Radiant Gold Editorial", sortOrder: 9, isPrimary: false },
      { id: "aur01-img-10", url: "/images/products/watches/velora-aurel-01/packaging.jpg", altText: "VELORA AUREL 01 Solid Wood Presentation Box", sortOrder: 10, isPrimary: false },
    ],
    variants: [
      { id: "aur01-v1", sku: "VEL-AUR-01-BRC", title: "Champagne Gold Brick-Link Bracelet", price: 145000, stock: 3, attributes: { bracelet: "Brick-Link Metal", clasp: "Concealed Butterfly" } },
      { id: "aur01-v2", sku: "VEL-AUR-01-LEA", title: "Honey Brown Leather Strap", price: 125000, stock: 4, attributes: { strap: "Honey Brown Leather", clasp: "Gold Clasp" } },
    ],
    macroDetails: [
      { part: "dial", title: "The Satin Champagne Dial", subtitle: "Sunburst Texture", description: "Warm golden dial with vertical satin graining catching natural light reflections.", imageUrl: "/images/products/watches/velora-aurel-01/dial-macro.jpg" },
      { part: "hands", title: "Polished Sword Hands", subtitle: "Mirrored Facets", description: "Hand-polished champagne gold hands offering pristine legibility.", imageUrl: "/images/products/watches/velora-aurel-01/front.jpg" },
      { part: "crown", title: "Integrated Crown", subtitle: "Natural Onyx Inset", description: "Subtly recessed into the case flank with an inlaid natural black onyx cabochon.", imageUrl: "/images/products/watches/velora-aurel-01/crown-macro.jpg" },
      { part: "case", title: "Champagne Gold Finish", subtitle: "Subtle Warm Luster", description: "Durable gold finish designed for an understated, modern brilliance.", imageUrl: "/images/products/watches/velora-aurel-01/case-macro.jpg" },
      { part: "strap", title: "Integrated Brick-Link Bracelet", subtitle: "Fluid Comfort", description: "Over 140 individually finished metal links articulating smoothly around the wrist.", imageUrl: "/images/products/watches/velora-aurel-01/strap-clasp.jpg" },
      { part: "clasp", title: "Concealed Butterfly Clasp", subtitle: "Seamless Closure", description: "Spring-loaded clasp mechanism disappearing cleanly beneath the continuous bracelet links.", imageUrl: "/images/products/watches/velora-aurel-01/strap-clasp.jpg" },
    ],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // 7. VELORA NOIR (FRAGRANCE)
  {
    id: "prod-frg-noir",
    name: "VELORA NOIR",
    slug: "velora-noir-extrait",
    sku: "VEL-FRG-NOIR",
    shortDescription: "A dark evening scent of smoked leather, birch wood, black pepper, and aged Cambodian agarwood.",
    description: "VELORA NOIR is an olfactory study of shadow, warmth, and quiet confidence. Opening with crisp black pepper and fresh bergamot, the heart reveals smoked leather, dry cedarwood, and frankincense. The base leaves an addictive trail of wild aged agarwood and vetiver, housed in a heavy smoked black glass bottle with a magnetic gunmetal cap.",
    price: 18500,
    compareAtPrice: 21000,
    cost: 6500,
    status: "PUBLISHED",
    featured: true,
    tags: ["Pure Perfume", "Smoked Leather", "Agarwood", "Noir", "Unisex"],
    concentration: "Pure Perfume (32% Oil Concentration)",
    olfactiveFamily: "Smoked Leather & Aged Wood",
    gender: "Unisex / Evening",
    volumeMl: 100,
    seoTitle: "VELORA NOIR Pure Perfume | Luxury Fragrance Pakistan",
    seoDescription: "32% pure perfume concentration with aged agarwood, smoked leather, birch wood, and frankincense.",
    category: { id: "cat-parfumerie", name: "Luxury Fragrances", slug: "high-perfumery" },
    collections: [
      { collection: { id: "col-noir", name: "Noir Black Collection", slug: "noir", bannerUrl: "/images/products/fragrances/velora-noir-extrait/editorial.jpg" } },
      { collection: { id: "col-nocturne", name: "Nocturne Evening Collection", slug: "nocturne-prive", bannerUrl: "/images/products/fragrances/velora-noir-extrait/lifestyle.jpg" } },
    ],
    inventory: { quantity: 42, warehouseLocation: "Lahore Central Vault" },
    images: [
      { id: "frg-noir-1", url: "/images/products/fragrances/velora-noir-extrait/bottle-front.jpg", altText: "VELORA NOIR 100ml Smoked Bottle", sortOrder: 1, isPrimary: true },
      { id: "frg-noir-2", url: "/images/products/fragrances/velora-noir-extrait/bottle-angle.jpg", altText: "VELORA NOIR Gunmetal Cap Angle", sortOrder: 2, isPrimary: false },
      { id: "frg-noir-3", url: "/images/products/fragrances/velora-noir-extrait/box.jpg", altText: "VELORA NOIR Velvet Presentation Box", sortOrder: 3, isPrimary: false },
      { id: "frg-noir-4", url: "/images/products/fragrances/velora-noir-extrait/lifestyle.jpg", altText: "VELORA NOIR Evening Scent Editorial", sortOrder: 4, isPrimary: false },
      { id: "frg-noir-5", url: "/images/products/fragrances/velora-noir-extrait/ingredient-notes.jpg", altText: "VELORA NOIR Rare Agarwood Notes", sortOrder: 5, isPrimary: false },
      { id: "frg-noir-6", url: "/images/products/fragrances/velora-noir-extrait/editorial.jpg", altText: "VELORA NOIR Campaign", sortOrder: 6, isPrimary: false },
      { id: "frg-noir-7", url: "/images/products/fragrances/velora-noir-extrait/gift-set.jpg", altText: "VELORA NOIR Gift Box Set", sortOrder: 7, isPrimary: false },
      { id: "frg-noir-8", url: "/images/products/fragrances/velora-noir-extrait/bottle-box.jpg", altText: "VELORA NOIR Bottle with Box", sortOrder: 8, isPrimary: false },
    ],
    variants: [
      { id: "frg-noir-v1", sku: "VEL-FRG-NOIR-100", title: "100ml Full Crystal Bottle", price: 18500, stock: 24, attributes: { size: "100ml", presentation: "Full Crystal Bottle" } },
      { id: "frg-noir-v2", sku: "VEL-FRG-NOIR-50", title: "50ml Travel Bottle with Leather Sheath", price: 12500, stock: 18, attributes: { size: "50ml", presentation: "Travel Leather Sheath" } },
    ],
    macroDetails: [
      { part: "flacon", title: "The Smoked Bottle", subtitle: "Heavy Glass", description: "Heavy dark smoked glass designed to protect delicate scent oils from sunlight.", imageUrl: "/images/products/fragrances/velora-noir-extrait/bottle-front.jpg" },
      { part: "cap", title: "The Gunmetal Cap", subtitle: "Magnetic Snap", description: "Solid cap coated in brushed gunmetal with a satisfying magnetic click closure.", imageUrl: "/images/products/fragrances/velora-noir-extrait/bottle-angle.jpg" },
      { part: "packaging", title: "The Presentation Box", subtitle: "Black Velvet Interior", description: "Rigid luxury gift box lined in soft black velvet with certificate of authenticity.", imageUrl: "/images/products/fragrances/velora-noir-extrait/box.jpg" },
      { part: "lifestyle", title: "Long-Lasting Trail", subtitle: "Over 14 Hours Longevity", description: "High concentration of pure perfume oils ensures a magnetic trail that lasts all day and evening.", imageUrl: "/images/products/fragrances/velora-noir-extrait/lifestyle.jpg" },
      { part: "notes", title: "Aged Agarwood", subtitle: "Pure Resins", description: "Wild agarwood slow-matured to preserve deep balsamic and woody notes.", imageUrl: "/images/products/fragrances/velora-noir-extrait/ingredient-notes.jpg" },
    ],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // 8. VELORA AURA (FRAGRANCE)
  {
    id: "prod-frg-aura",
    name: "VELORA AURA",
    slug: "velora-aura-extrait",
    sku: "VEL-FRG-AURA",
    shortDescription: "Fresh citrus, golden jasmine, warm white amber, and clean cedarwood.",
    description: "An uplifting daytime fragrance filled with warmth and radiance. VELORA AURA opens with sparkling Italian citrus and white florals before settling into a luminous heart of jasmine petals and sweet neroli. The base leaves a cozy warmth of white amber and soft cedarwood. Housed in a frosted glass bottle with a golden stopper.",
    price: 16500,
    compareAtPrice: 19000,
    cost: 5800,
    status: "PUBLISHED",
    featured: true,
    tags: ["Pure Perfume", "Citrus", "Jasmine", "Amber", "Luminous"],
    concentration: "Pure Perfume (30% Oil Concentration)",
    olfactiveFamily: "Solar Floral & Golden Amber",
    gender: "Unisex / Uplifting",
    volumeMl: 100,
    seoTitle: "VELORA AURA Pure Perfume | Luxury Fragrance Pakistan",
    seoDescription: "30% pure perfume oil concentration with bergamot, fresh jasmine, white amber, and coastal cedar.",
    category: { id: "cat-parfumerie", name: "Luxury Fragrances", slug: "high-perfumery" },
    collections: [
      { collection: { id: "col-signature", name: "Signature Collection", slug: "signature", bannerUrl: "/images/products/watches/velora-signature-01/editorial.jpg" } },
    ],
    inventory: { quantity: 45, warehouseLocation: "Karachi Central Vault" },
    images: [
      { id: "frg-aura-1", url: "/images/products/fragrances/velora-aura-extrait/bottle-front.jpg", altText: "VELORA AURA 100ml Frosted Bottle", sortOrder: 1, isPrimary: true },
      { id: "frg-aura-2", url: "/images/products/fragrances/velora-aura-extrait/bottle-angle.jpg", altText: "VELORA AURA Gold Cap Angle", sortOrder: 2, isPrimary: false },
      { id: "frg-aura-3", url: "/images/products/fragrances/velora-aura-extrait/box.jpg", altText: "VELORA AURA Ivory Presentation Box", sortOrder: 3, isPrimary: false },
      { id: "frg-aura-4", url: "/images/products/fragrances/velora-aura-extrait/lifestyle.jpg", altText: "VELORA AURA Daytime Wear Editorial", sortOrder: 4, isPrimary: false },
      { id: "frg-aura-5", url: "/images/products/fragrances/velora-aura-extrait/ingredient-notes.jpg", altText: "VELORA AURA Jasmine & Citrus Notes", sortOrder: 5, isPrimary: false },
      { id: "frg-aura-6", url: "/images/products/fragrances/velora-aura-extrait/editorial.jpg", altText: "VELORA AURA Campaign", sortOrder: 6, isPrimary: false },
      { id: "frg-aura-7", url: "/images/products/fragrances/velora-aura-extrait/gift-set.jpg", altText: "VELORA AURA Gift Set", sortOrder: 7, isPrimary: false },
      { id: "frg-aura-8", url: "/images/products/fragrances/velora-aura-extrait/bottle-box.jpg", altText: "VELORA AURA Packaging", sortOrder: 8, isPrimary: false },
    ],
    variants: [
      { id: "frg-aura-v1", sku: "VEL-FRG-AURA-100", title: "100ml Frosted Crystal Bottle", price: 16500, stock: 30, attributes: { size: "100ml", presentation: "Full Crystal Bottle" } },
      { id: "frg-aura-v2", sku: "VEL-FRG-AURA-50", title: "50ml Travel Bottle with Gold Sheath", price: 11000, stock: 15, attributes: { size: "50ml", presentation: "Travel Gold Sheath" } },
    ],
    macroDetails: [
      { part: "flacon", title: "The Frosted Bottle", subtitle: "Soft Amber Tint", description: "Satin-frosted glass catching natural daylight with a warm golden glow.", imageUrl: "/images/products/fragrances/velora-aura-extrait/bottle-front.jpg" },
      { part: "cap", title: "The Gold Cap", subtitle: "Polished Finish", description: "Heavyweight gold-tone stopper engraved with the minimalist VELORA crest.", imageUrl: "/images/products/fragrances/velora-aura-extrait/bottle-angle.jpg" },
      { part: "packaging", title: "The Ivory Gift Box", subtitle: "Gold Foil Monogram", description: "Warm ivory rigid box with gold foil lettering and satin pull ribbon.", imageUrl: "/images/products/fragrances/velora-aura-extrait/box.jpg" },
      { part: "lifestyle", title: "Radiant Daytime Trail", subtitle: "Clean Scent", description: "Effortlessly elegant projection leaving a clean, sun-warmed amber impression.", imageUrl: "/images/products/fragrances/velora-aura-extrait/lifestyle.jpg" },
      { part: "notes", title: "Citrus & Jasmine", subtitle: "Fresh Extraction", description: "Cold-pressed citrus rind harmonized with night-blooming jasmine petals.", imageUrl: "/images/products/fragrances/velora-aura-extrait/ingredient-notes.jpg" },
    ],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // 9. VELORA ÉLAN (FRAGRANCE)
  {
    id: "prod-frg-elan",
    name: "VELORA ÉLAN",
    slug: "velora-elan-extrait",
    sku: "VEL-FRG-ELAN",
    shortDescription: "Highland juniper berry, fresh green cypress, crushed violet leaves, and earthy vetiver roots.",
    description: "Crisp, clean, and refreshing. VELORA ÉLAN captures the vitality of cool mountain mornings. Top notes of wild juniper and crushed mint give way to green violet leaves and pine needle. The finish is anchored by earthy vetiver roots and clean cedarwood, housed in deep emerald green glass with a silver stopper.",
    price: 17000,
    compareAtPrice: 19500,
    cost: 5900,
    status: "PUBLISHED",
    featured: true,
    tags: ["Pure Perfume", "Aromatic Green", "Vetiver", "Fresh Luxury", "Unisex"],
    concentration: "Pure Perfume (30% Oil Concentration)",
    olfactiveFamily: "Green Aromatic & Fresh Woods",
    gender: "Unisex / Fresh",
    volumeMl: 100,
    seoTitle: "VELORA ÉLAN Pure Perfume | Luxury Fragrance Pakistan",
    seoDescription: "30% pure perfume oil concentration with highland juniper, crisp cypress, violet leaves, and vetiver.",
    category: { id: "cat-parfumerie", name: "Luxury Fragrances", slug: "high-perfumery" },
    collections: [
      { collection: { id: "col-classic", name: "Classic Heritage Collection", slug: "classic", bannerUrl: "/images/products/watches/velora-classic-01/editorial.jpg" } },
    ],
    inventory: { quantity: 32, warehouseLocation: "Islamabad Central Vault" },
    images: [
      { id: "frg-elan-1", url: "/images/products/fragrances/velora-elan-extrait/bottle-front.jpg", altText: "VELORA ÉLAN 100ml Emerald Bottle", sortOrder: 1, isPrimary: true },
      { id: "frg-elan-2", url: "/images/products/fragrances/velora-elan-extrait/bottle-angle.jpg", altText: "VELORA ÉLAN Silver Stopper", sortOrder: 2, isPrimary: false },
      { id: "frg-elan-3", url: "/images/products/fragrances/velora-elan-extrait/box.jpg", altText: "VELORA ÉLAN Green Box", sortOrder: 3, isPrimary: false },
      { id: "frg-elan-4", url: "/images/products/fragrances/velora-elan-extrait/lifestyle.jpg", altText: "VELORA ÉLAN Fresh Editorial", sortOrder: 4, isPrimary: false },
      { id: "frg-elan-5", url: "/images/products/fragrances/velora-elan-extrait/ingredient-notes.jpg", altText: "VELORA ÉLAN Juniper & Vetiver Notes", sortOrder: 5, isPrimary: false },
      { id: "frg-elan-6", url: "/images/products/fragrances/velora-elan-extrait/editorial.jpg", altText: "VELORA ÉLAN Campaign", sortOrder: 6, isPrimary: false },
      { id: "frg-elan-7", url: "/images/products/fragrances/velora-elan-extrait/gift-set.jpg", altText: "VELORA ÉLAN Gift Box", sortOrder: 7, isPrimary: false },
      { id: "frg-elan-8", url: "/images/products/fragrances/velora-elan-extrait/bottle-box.jpg", altText: "VELORA ÉLAN Bottle with Box", sortOrder: 8, isPrimary: false },
    ],
    variants: [
      { id: "frg-elan-v1", sku: "VEL-FRG-ELAN-100", title: "100ml Forest Emerald Bottle", price: 17000, stock: 20, attributes: { size: "100ml", presentation: "Full Crystal Bottle" } },
      { id: "frg-elan-v2", sku: "VEL-FRG-ELAN-50", title: "50ml Travel Bottle with Silver Sheath", price: 11500, stock: 12, attributes: { size: "50ml", presentation: "Travel Silver Sheath" } },
    ],
    macroDetails: [
      { part: "flacon", title: "The Emerald Bottle", subtitle: "Deep Pine Tint", description: "Glass tinted with natural green minerals yielding an emerald translucence.", imageUrl: "/images/products/fragrances/velora-elan-extrait/bottle-front.jpg" },
      { part: "cap", title: "The Silver Cap", subtitle: "Mirror-Polished", description: "Solid cap with bright chrome finish resisting tarnish and scratches.", imageUrl: "/images/products/fragrances/velora-elan-extrait/bottle-angle.jpg" },
      { part: "packaging", title: "The Green Gift Box", subtitle: "Textured Paper", description: "Forest green presentation box debossed with botanical leaf patterns.", imageUrl: "/images/products/fragrances/velora-elan-extrait/box.jpg" },
      { part: "lifestyle", title: "Crisp Mountain Trail", subtitle: "Invigorating Scent", description: "Clean, fresh, and remarkably enduring without synthetic harshness.", imageUrl: "/images/products/fragrances/velora-elan-extrait/lifestyle.jpg" },
      { part: "notes", title: "Juniper & Vetiver", subtitle: "Natural Essences", description: "Wild-harvested juniper berries distilled for exceptional aromatic clarity.", imageUrl: "/images/products/fragrances/velora-elan-extrait/ingredient-notes.jpg" },
    ],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // 10. VELORA OUD (FRAGRANCE)
  {
    id: "prod-frg-oud",
    name: "VELORA OUD",
    slug: "velora-oud-extrait",
    sku: "VEL-FRG-OUD",
    shortDescription: "Rare aged Cambodian agarwood, Iranian saffron threads, velvety Taif rose, and warm balsamic amber.",
    description: "The crown jewel of our fragrance collection. Formulated at an exceptional 35% perfume oil concentration, VELORA OUD uses wild agarwood naturally matured for fifteen years. Layered with crimson threads of saffron, royal rose petals, and smoldering amber resins. Housed in a heavy cognac-amber glass bottle with an antiqued bronze cap.",
    price: 22500,
    compareAtPrice: 25000,
    cost: 8000,
    status: "PUBLISHED",
    featured: true,
    tags: ["Pure Perfume", "Cambodian Oud", "Taif Rose", "Saffron", "Opulent"],
    concentration: "Pure Perfume (35% Oil Concentration)",
    olfactiveFamily: "Oriental Woody & Rich Spice",
    gender: "Unisex / Opulent",
    volumeMl: 100,
    seoTitle: "VELORA OUD Pure Perfume | Luxury Fragrance Pakistan",
    seoDescription: "35% concentration wild Cambodian agarwood matured 15 years, saffron threads, and velvet rose.",
    category: { id: "cat-parfumerie", name: "Luxury Fragrances", slug: "high-perfumery" },
    collections: [
      { collection: { id: "col-nocturne", name: "Nocturne Evening Collection", slug: "nocturne-prive", bannerUrl: "/images/products/fragrances/velora-noir-extrait/lifestyle.jpg" } },
    ],
    inventory: { quantity: 25, warehouseLocation: "Lahore Central Vault" },
    images: [
      { id: "frg-oud-1", url: "/images/products/fragrances/velora-oud-extrait/bottle-front.jpg", altText: "VELORA OUD 100ml Amber Bottle", sortOrder: 1, isPrimary: true },
      { id: "frg-oud-2", url: "/images/products/fragrances/velora-oud-extrait/bottle-angle.jpg", altText: "VELORA OUD Bronze Stopper", sortOrder: 2, isPrimary: false },
      { id: "frg-oud-3", url: "/images/products/fragrances/velora-oud-extrait/box.jpg", altText: "VELORA OUD Luxury Box", sortOrder: 3, isPrimary: false },
      { id: "frg-oud-4", url: "/images/products/fragrances/velora-oud-extrait/lifestyle.jpg", altText: "VELORA OUD Scent Editorial", sortOrder: 4, isPrimary: false },
      { id: "frg-oud-5", url: "/images/products/fragrances/velora-oud-extrait/ingredient-notes.jpg", altText: "VELORA OUD Aged Agarwood & Saffron", sortOrder: 5, isPrimary: false },
      { id: "frg-oud-6", url: "/images/products/fragrances/velora-oud-extrait/editorial.jpg", altText: "VELORA OUD Campaign", sortOrder: 6, isPrimary: false },
      { id: "frg-oud-7", url: "/images/products/fragrances/velora-oud-extrait/gift-set.jpg", altText: "VELORA OUD Gift Set", sortOrder: 7, isPrimary: false },
      { id: "frg-oud-8", url: "/images/products/fragrances/velora-oud-extrait/bottle-box.jpg", altText: "VELORA OUD Presentation Ensemble", sortOrder: 8, isPrimary: false },
    ],
    variants: [
      { id: "frg-oud-v1", sku: "VEL-FRG-OUD-100", title: "100ml Amber Cognac Crystal Bottle", price: 22500, stock: 15, attributes: { size: "100ml", presentation: "Full Crystal Bottle" } },
      { id: "frg-oud-v2", sku: "VEL-FRG-OUD-50", title: "50ml Travel Bottle with Bronze Sheath", price: 15000, stock: 10, attributes: { size: "50ml", presentation: "Travel Bronze Sheath" } },
    ],
    macroDetails: [
      { part: "flacon", title: "The Amber Bottle", subtitle: "Heavy Crystal Glass", description: "Warm amber-tinted crystal reflecting liquid golden hues under warm light.", imageUrl: "/images/products/fragrances/velora-oud-extrait/bottle-front.jpg" },
      { part: "cap", title: "The Bronze Cap", subtitle: "Fluted Finish", description: "Cast bronze cap featuring classical vertical fluting and monogram seal.", imageUrl: "/images/products/fragrances/velora-oud-extrait/bottle-angle.jpg" },
      { part: "packaging", title: "The Royal Box", subtitle: "Bronze Foil Accents", description: "Opulent presentation box featuring bronze metallic foil and velvet-padded bottle bed.", imageUrl: "/images/products/fragrances/velora-oud-extrait/box.jpg" },
      { part: "lifestyle", title: "The 24-Hour Trail", subtitle: "35% Concentration", description: "A profound, hypnotic trail that lingers gracefully on fabric and skin for over 24 hours.", imageUrl: "/images/products/fragrances/velora-oud-extrait/lifestyle.jpg" },
      { part: "notes", title: "15-Year Aged Oud", subtitle: "Pure Wild Harvest", description: "Rich, deep, and remarkably smooth agarwood aged to perfection.", imageUrl: "/images/products/fragrances/velora-oud-extrait/ingredient-notes.jpg" },
    ],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // 11. VELORA SANTÉ (FRAGRANCE)
  {
    id: "prod-frg-sante",
    name: "VELORA SANTÉ",
    slug: "velora-sante-extrait",
    sku: "VEL-FRG-SANTE",
    shortDescription: "White tea leaves, crisp pear, gentle rosewater, and soft crystalline musk.",
    description: "A tranquil breath of calm and graceful restraint. VELORA SANTÉ opens with fresh white peach, sparkling sweet pear, and steepings of rare silver needle white tea. As it warms on the skin, tender rose petals and iris bloom over a whisper-soft base of clean musk and light sandalwood. Housed in a fluted glass column with a rose gold collar.",
    price: 15500,
    compareAtPrice: 17500,
    cost: 5200,
    status: "PUBLISHED",
    featured: true,
    tags: ["Pure Perfume", "White Tea", "Pear", "Damask Rose", "Ethereal"],
    concentration: "Pure Perfume (28% Oil Concentration)",
    olfactiveFamily: "Soft Floral & Mineral Tea",
    gender: "Unisex / Gentle",
    volumeMl: 100,
    seoTitle: "VELORA SANTÉ Pure Perfume | Luxury Fragrance Pakistan",
    seoDescription: "28% pure perfume concentration featuring silver needle white tea, crisp pear, gentle rose, and soft musk.",
    category: { id: "cat-parfumerie", name: "Luxury Fragrances", slug: "high-perfumery" },
    collections: [
      { collection: { id: "col-signature", name: "Signature Collection", slug: "signature", bannerUrl: "/images/products/watches/velora-signature-01/editorial.jpg" } },
    ],
    inventory: { quantity: 36, warehouseLocation: "Karachi Central Vault" },
    images: [
      { id: "frg-sante-1", url: "/images/products/fragrances/velora-sante-extrait/bottle-front.jpg", altText: "VELORA SANTÉ 100ml Fluted Bottle", sortOrder: 1, isPrimary: true },
      { id: "frg-sante-2", url: "/images/products/fragrances/velora-sante-extrait/bottle-angle.jpg", altText: "VELORA SANTÉ Rose Gold Collar", sortOrder: 2, isPrimary: false },
      { id: "frg-sante-3", url: "/images/products/fragrances/velora-sante-extrait/box.jpg", altText: "VELORA SANTÉ Ivory & Blush Box", sortOrder: 3, isPrimary: false },
      { id: "frg-sante-4", url: "/images/products/fragrances/velora-sante-extrait/lifestyle.jpg", altText: "VELORA SANTÉ Morning Editorial", sortOrder: 4, isPrimary: false },
      { id: "frg-sante-5", url: "/images/products/fragrances/velora-sante-extrait/ingredient-notes.jpg", altText: "VELORA SANTÉ White Tea & Pear Notes", sortOrder: 5, isPrimary: false },
      { id: "frg-sante-6", url: "/images/products/fragrances/velora-sante-extrait/editorial.jpg", altText: "VELORA SANTÉ Botanical Campaign", sortOrder: 6, isPrimary: false },
      { id: "frg-sante-7", url: "/images/products/fragrances/velora-sante-extrait/gift-set.jpg", altText: "VELORA SANTÉ Gift Set", sortOrder: 7, isPrimary: false },
      { id: "frg-sante-8", url: "/images/products/fragrances/velora-sante-extrait/bottle-box.jpg", altText: "VELORA SANTÉ Packaging", sortOrder: 8, isPrimary: false },
    ],
    variants: [
      { id: "frg-sante-v1", sku: "VEL-FRG-SANTE-100", title: "100ml Fluted Glass Column Bottle", price: 15500, stock: 22, attributes: { size: "100ml", presentation: "Full Crystal Bottle" } },
      { id: "frg-sante-v2", sku: "VEL-FRG-SANTE-50", title: "50ml Travel Bottle with Rose Gold Sheath", price: 10500, stock: 14, attributes: { size: "50ml", presentation: "Travel Rose Gold Sheath" } },
    ],
    macroDetails: [
      { part: "flacon", title: "The Fluted Column", subtitle: "Classical Grooves", description: "Slender fluted glass creating subtle light reflections on dressing tables.", imageUrl: "/images/products/fragrances/velora-sante-extrait/bottle-front.jpg" },
      { part: "cap", title: "The Rose Gold Collar", subtitle: "Blush Metallic Accent", description: "Subtle rose gold plated collar and cap with blush silk tassel accent.", imageUrl: "/images/products/fragrances/velora-sante-extrait/bottle-angle.jpg" },
      { part: "packaging", title: "The Ivory & Blush Box", subtitle: "Rose Gold Lettering", description: "Minimalist cream presentation box featuring understated rose gold typography.", imageUrl: "/images/products/fragrances/velora-sante-extrait/box.jpg" },
      { part: "lifestyle", title: "Gentle Scent Trail", subtitle: "Clean Sillage", description: "Light, pleasant projection evoking quiet mornings and peaceful tea gardens.", imageUrl: "/images/products/fragrances/velora-sante-extrait/lifestyle.jpg" },
      { part: "notes", title: "White Tea & Pear", subtitle: "Delicate Infusion", description: "First-harvest tea buds steeped cold to retain gentle floral sweetness.", imageUrl: "/images/products/fragrances/velora-sante-extrait/ingredient-notes.jpg" },
    ],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
];

export const FALLBACK_JOURNAL_POSTS: CatalogJournalPost[] = [
  {
    id: "post-1",
    title: "The Architecture of the Balance Wheel: Precision in Watchmaking",
    slug: "architecture-of-the-free-sprung-balance-wheel",
    subtitle: "How balanced weights and fine tuning achieve reliable mechanical timekeeping",
    excerpt: "An exploration of mechanical balance wheels, temperature compensation, and how VELORA achieves 68 hours of uninterrupted power reserve.",
    category: "Watches",
    authorName: "Master Watchmaker",
    author: { firstName: "Ahmed", lastName: "Khan" },
    coverImageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1600&q=85",
    isPublished: true,
    publishedAt: "2026-08-15T10:00:00.000Z",
    seoTitle: "Watchmaking Balance Wheels & Precision | VELORA Journal",
    seoDescription: "Discover how VELORA tunes automatic mechanical balance wheels for daily reliability and precision.",
    ogImage: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=85",
    canonicalUrl: "https://velorawatches.pk/journal/architecture-of-the-free-sprung-balance-wheel",
    relatedProductIds: ["prod-sig-01", "prod-sig-02"],
    content: `In high-grade mechanical watchmaking, time is counted through precision physics. Inside every automatic movement, the regulating organ—the balance wheel and hairspring—dictates how accurately the timepiece keeps time.

By utilizing micro-screws along the rim of the balance wheel, our watchmakers adjust poise and rate with extreme care. The result is pure, uninterrupted timekeeping that remains stable against daily shocks and temperature changes.

> "A well-tuned balance wheel beats with natural rhythm, undisturbed by outside friction."

## Hand-Finished Edges and Polishing

Beyond physics, mechanical watchmaking requires artisan craftsmanship. Every bridge securing our movement is mirror-polished by hand. Sharp internal angles are hand-beveled under magnification.

When you observe the heartbeat of Calibre VA-01 through the sapphire exhibition caseback, you witness genuine horological dedication beating at 28,800 vibrations per hour.`,
  },
  {
    id: "post-2",
    title: "The Art of Concentrated Perfume: Why 35% Pure Oil Matters",
    slug: "nocturne-dark-art-of-extraction",
    subtitle: "How cold extraction of rare agarwood and roses creates deep, long-lasting scent",
    excerpt: "Inside our fragrance laboratory: formulating pure perfumes that linger gracefully for over twenty-four hours on skin and fabrics.",
    category: "Perfumes",
    authorName: "Fragrance Director",
    author: { firstName: "Zainab", lastName: "Malik" },
    coverImageUrl: "https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?auto=format&fit=crop&w=1600&q=85",
    isPublished: true,
    publishedAt: "2026-07-28T14:30:00.000Z",
    seoTitle: "The Art of Concentrated Perfume | VELORA Journal",
    seoDescription: "Learn why VELORA formulates pure perfumes at 30% to 35% oil concentration for unrivaled projection.",
    ogImage: "https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?auto=format&fit=crop&w=1200&q=85",
    canonicalUrl: "https://velorawatches.pk/journal/nocturne-dark-art-of-extraction",
    relatedProductIds: ["prod-frg-noir", "prod-frg-oud"],
    content: `Most commercial perfumes contain only 10% to 15% fragrance oil, diluted heavily with alcohol and fillers. At VELORA, we formulate exclusively at high concentrations between 30% and 35%.

> "At 35% pure perfume oil concentration, a fragrance does not shout. It stays close with an intimate, velvet trail that endures through day and night."

## Gentle Low-Temperature Distillation

Traditional steam methods can overheat delicate petals and aged woods. We utilize low-temperature extraction to capture the natural essence of wild Cambodian agarwood, pure saffron, and fresh rose petals without burning fragile top notes.

The extracted oils rest in dark vessels for four months, allowing the complex woods, resins, and florals to marry before being hand-bottled into heavy crystal bottles.`,
  },
  {
    id: "post-3",
    title: "Hardened Titanium & Steel: Metallurgy for Everyday Luxury",
    slug: "monochrome-and-metallurgy-dlc-titanium",
    subtitle: "Combining lightweight aerospace titanium with scratch-resistant diamond-like carbon",
    excerpt: "Why modern luxury watches demand materials that resist daily wear while remaining featherlight on the wrist.",
    category: "Craftsmanship",
    authorName: "Materials Engineering",
    author: { firstName: "Bilal", lastName: "Siddiqui" },
    coverImageUrl: "https://images.unsplash.com/photo-1547996160-71dfabb1d0a5?auto=format&fit=crop&w=1600&q=85",
    isPublished: true,
    publishedAt: "2026-06-12T09:15:00.000Z",
    seoTitle: "Hardened Titanium & Steel Metallurgy | VELORA Journal",
    seoDescription: "How VELORA uses Grade 5 Titanium and DLC coatings for scratch-resistant luxury watches.",
    ogImage: "https://images.unsplash.com/photo-1547996160-71dfabb1d0a5?auto=format&fit=crop&w=1200&q=85",
    canonicalUrl: "https://velorawatches.pk/journal/monochrome-and-metallurgy-dlc-titanium",
    relatedProductIds: ["prod-noir-01", "prod-noir-02"],
    content: `A luxury timepiece must not only look distinguished; it must withstand decades of active daily wear.

Grade 5 Titanium is twice as light as steel yet possesses superior tensile strength. By applying a microscopic Diamond-Like Carbon (DLC) coating via physical vapor deposition, the outer surface achieves extreme scratch resistance while maintaining an understated velvet matte black appearance.

> "A watch should feel like an extension of your wrist—effortless, resilient, and unmistakably refined."

Whether you wear the surgical 904L steel SIGNATURE 01 or the titanium NOIR 01, each case is finished to perfection.`,
  },
];

export const FALLBACK_HOMEPAGE_SECTIONS = [
  {
    id: "sec-hero",
    sectionKey: "hero_main",
    name: "Hero Section",
    title: "TIME, REFINED.",
    subtitle: "Pakistan's premier luxury watches and pure concentrated perfumes.",
    content: {
      eyebrow: "VELORA PAKISTAN",
      ctaText: "Discover The Collection",
      ctaLink: "/collections/signature",
      secondaryCtaText: "Explore Watches",
      secondaryCtaLink: "/watches",
      bgImageUrl: "/images/products/watches/velora-signature-01/editorial.jpg",
    },
    sortOrder: 1,
    isActive: true,
  },
  {
    id: "sec-featured-watch",
    sectionKey: "featured_watch",
    name: "Featured Watch",
    title: "VELORA SIGNATURE 01",
    subtitle: "The Archetype of Precision and Restraint",
    content: {
      productSlug: "velora-signature-01",
      badge: "Flagship Edition",
      description: "Our signature 39mm automatic watch crafted in surgical 904L steel with an opaline ivory dial, heat-blued hands, and 68 hours of power reserve. Delivered with open parcel inspection and our 7-day checking warranty across Pakistan.",
      ctaText: "View Details",
      ctaLink: "/product/velora-signature-01",
    },
    sortOrder: 2,
    isActive: true,
  },
  {
    id: "sec-collection-story",
    sectionKey: "collection_story",
    name: "Collection Story",
    title: "A Study in Restraint",
    subtitle: "Where Mechanical Precision Meets Olfactory Art",
    content: {
      quote: "We believe true luxury is found not in excess, but in the perfection of essential lines and honest materials.",
      author: "VELORA Pakistan Philosophy",
      ctaText: "Discover Our Collections",
      ctaLink: "/collections",
    },
    sortOrder: 3,
    isActive: true,
  },
  {
    id: "sec-collections-grid",
    sectionKey: "collections_grid",
    name: "Collections Grid",
    title: "The Collections",
    subtitle: "Three Distinct Expressions of Modern Horology",
    content: {
      signatureTitle: "Signature Collection",
      signatureSubtitle: "Purity of form and everyday balance",
      noirTitle: "Noir Black Collection",
      noirSubtitle: "Shadowed titanium and scratch-proof ceramic",
      classicTitle: "Classic Heritage Collection",
      classicSubtitle: "Porcelain dials and ultra-thin silhouettes",
    },
    sortOrder: 4,
    isActive: true,
  },
  {
    id: "sec-split",
    sectionKey: "watch_fragrance_split",
    name: "Watch & Fragrance Split",
    title: "Two Disciplines. One Brand.",
    subtitle: "Precision Watches & Pure Concentrated Perfumes in Pakistan.",
    content: {
      timeTitle: "Luxury Watches",
      timeSubtitle: "Automatic Movements",
      timeDescription: "Hand-assembled timepieces built with sapphire crystal and 7-day checking warranty.",
      timeCtaText: "Discover Watches",
      timeCtaLink: "/watches",
      timeImageUrl: "/images/products/watches/velora-signature-01/editorial.jpg",
      fragranceTitle: "Luxury Fragrances",
      fragranceSubtitle: "Pure Concentrated Perfumes",
      fragranceDescription: "Aged agarwood, fresh citrus, and long-lasting floral essences in crystal bottles.",
      fragranceCtaText: "Discover Fragrances",
      fragranceCtaLink: "/fragrances",
      fragranceImageUrl: "/images/products/fragrances/velora-noir-extrait/editorial.jpg",
    },
    sortOrder: 5,
    isActive: true,
  },
  {
    id: "sec-signature-product",
    sectionKey: "signature_product",
    name: "Signature Product Spotlight",
    title: "Crafted for Generations",
    subtitle: "VELORA SIGNATURE 01",
    content: {
      productSlug: "velora-signature-01",
      ctaText: "Order Online",
      specs: [
        { label: "Movement", value: "Automatic Calibre VA-01" },
        { label: "Case", value: "39mm 904L Stainless Steel" },
        { label: "Power Reserve", value: "68 Hours" },
        { label: "Crystal", value: "Double-Domed Sapphire" },
      ],
    },
    sortOrder: 6,
    isActive: true,
  },
  {
    id: "sec-craftsmanship",
    sectionKey: "craftsmanship_gallery",
    name: "Craftsmanship Gallery",
    title: "Macro Details",
    subtitle: "Precision Finishings Inspected to the Micron",
    content: {},
    sortOrder: 7,
    isActive: true,
  },
  {
    id: "sec-fragrance-editorial",
    sectionKey: "fragrance_editorial",
    name: "Fragrance Editorial",
    title: "Pure Concentrated Perfumes",
    subtitle: "Crafted with 30% to 35% Pure Perfume Oil for Maximum Longevity",
    content: {
      highlightFragranceSlug: "velora-noir-extrait",
      ctaText: "Explore Fragrances",
      ctaLink: "/fragrances",
    },
    sortOrder: 8,
    isActive: true,
  },
  {
    id: "sec-gifting",
    sectionKey: "gifting_packaging",
    name: "Gifting & Packaging",
    title: "The Unboxing Ritual",
    subtitle: "Every order arrives in handcrafted presentation packaging with our checking warranty card and verification details.",
    content: {
      imageUrl: "/images/products/watches/velora-signature-01/packaging.jpg",
    },
    sortOrder: 9,
    isActive: true,
  },
  {
    id: "sec-brand-story",
    sectionKey: "brand_story",
    name: "Brand Story",
    title: "Heritage & Craft in Pakistan",
    subtitle: "Dedicated to creating world-class mechanical watches and pure concentrated perfumes for Pakistan and beyond.",
    content: {
      ctaText: "Explore Collections",
      ctaLink: "/collections",
    },
    sortOrder: 10,
    isActive: true,
  },
  {
    id: "sec-delivery-concierge",
    sectionKey: "delivery_concierge",
    name: "Courier & Concierge Services",
    title: "Nationwide Courier & Concierge Care",
    subtitle: "Complimentary express delivery across Pakistan via TCS, Leopard, Trax, and Call Courier with Cash on Delivery.",
    content: {},
    sortOrder: 11,
    isActive: true,
  },
  {
    id: "sec-newsletter",
    sectionKey: "newsletter_section",
    name: "Newsletter Section",
    title: "Join the VELORA Circle",
    subtitle: "Subscribe for private release announcements, VIP previews, and exclusive invitations in Pakistan.",
    content: {},
    sortOrder: 12,
    isActive: true,
  },
];
